// this is autogenerated file: do not edit
// clang-format off
#ifndef system_colorpanel_tcl_h_
#define system_colorpanel_tcl_h_
constexpr const char* system_colorpanel_tcl = 
"namespace eval ::ceammc::colorpanel:: {}\n"
"proc ::ceammc::colorpanel::parse_zenity {str} {\n"
"    set raw [string trim $str]\n"
"    # parse rgb(r,g,b) or rgba(r,g,b,a)\n"
"    if {[regexp {rgb[a]?\\((\\d+),(\\d+),(\\d+)} $raw -> r g b]} {\n"
"        return [format \"#%02x%02x%02x\" $r $g $b]\n"
"    } else {\n"
"        return $raw\n"
"    }\n"
"}\n"
"proc ::ceammc::colorpanel::do_open {objectid initialcolor} {\n"
"    set color {}\n"
"    switch $::windowingsystem {\n"
"        \"x11\" {\n"
"            set cmd \"exec zenity --color-selection --title=Color --color=$initialcolor\"\n"
"            ::pdwindow::error \"$cmd\\n\"\n"
"            if {[catch $cmd result]} {\n"
"                return\n"
"            }\n"
"            set color [::ceammc::colorpanel::parse_zenity $result]\n"
"        }\n"
"        default {\n"
"            set color [tk_chooseColor -initialcolor $initialcolor]\n"
"        }\n"
"    }\n"
"    if {$color ne \"\"} {\n"
"        pdsend \"$objectid .tcl_callback $color\"\n"
"    }\n"
"}\n"
"proc ::ceammc::colorpanel::open {objectid initialcolor} {\n"
"    after idle [list after 100 ::ceammc::colorpanel::do_open $objectid $initialcolor]\n"
"}\n"
;
#endif
// clang-format on
