.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ceam-util-xdg-info 1  "info " 
.SH NAME
ceam\-util\-xdg\-info \- xdg MIME type and default application info
.SH SYNOPSIS
\fBceam\-util xdg info\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
xdg MIME type and default application info
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
