.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ceam-util-pd-lang 1  "lang " 
.SH NAME
ceam\-util\-pd\-lang \- set PureData doc language (for ceammc external)
.SH SYNOPSIS
\fBceam\-util pd lang\fR [\fB\-s\fR|\fB\-\-set\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
set PureData doc language (for ceammc external)
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-set\fR \fI<SET>\fR
language name code
.br

.br
[\fIpossible values: \fRru, en, default]
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
