.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ceam-util 1  "ceam-util 0.1.1" 
.SH NAME
ceam\-util \- CEAM utilities
.SH SYNOPSIS
\fBceam\-util\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
CEAM utilities
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
ceam\-util\-pd(1)
PureData control
.TP
ceam\-util\-info(1)
System information
.SH VERSION
v0.1.1
