.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ceam-util-keyboard-info 1  "info " 
.SH NAME
ceam\-util\-keyboard\-info \- print keyboard layout information
.SH SYNOPSIS
\fBceam\-util keyboard info\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
print keyboard layout information
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
