.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ceam-util-keyboard 1  "keyboard " 
.SH NAME
ceam\-util\-keyboard \- keyboard layout
.SH SYNOPSIS
\fBceam\-util keyboard\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
keyboard layout
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
ceam\-util\-keyboard\-fix(1)
fix keyboard layout change
.TP
ceam\-util\-keyboard\-info(1)
print keyboard layout information
