.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ceam-util-info 1  "info " 
.SH NAME
ceam\-util\-info \- System information
.SH SYNOPSIS
\fBceam\-util info\fR [\fB\-u\fR|\fB\-\-use\-bytes\fR] [\fB\-a\fR|\fB\-\-all\fR] [\fB\-\-mem\fR] [\fB\-\-cpu\fR] [\fB\-\-system\fR] [\fB\-\-pd\fR] [\fB\-\-net\fR] [\fB\-\-disk\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
System information
.SH OPTIONS
.TP
\fB\-u\fR, \fB\-\-use\-bytes\fR
use bytes in output
.TP
\fB\-a\fR, \fB\-\-all\fR
output all information
.TP
\fB\-\-mem\fR
output memory information
.TP
\fB\-\-cpu\fR
output cpu information
.TP
\fB\-\-system\fR
output system information
.TP
\fB\-\-pd\fR
output PureData information (default)
.TP
\fB\-\-net\fR
output network information
.TP
\fB\-\-disk\fR
output disks information
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
