.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ceam-util-pd 1  "pd " 
.SH NAME
ceam\-util\-pd \- PureData control
.SH SYNOPSIS
\fBceam\-util pd\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
PureData control
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
ceam\-util\-pd\-autostart(1)
auto start control: enable, disable, set main patch symlink
.TP
ceam\-util\-pd\-lang(1)
set PureData doc language (for ceammc external)
.TP
ceam\-util\-pd\-update(1)
update CEAMMC PureData
