.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ceam-util-keyboard-fix 1  "fix " 
.SH NAME
ceam\-util\-keyboard\-fix \- fix keyboard layout change
.SH SYNOPSIS
\fBceam\-util keyboard fix\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
fix keyboard layout change
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
