#!/bin/bash

GCC=gcc
SRC_PATH="$(dirname $0)/../.."

echo $SRC_PATH
cmake -DWITH_COVERAGE=ON -DWITH_PORTMIDI=OFF -DWITH_DUMMY=ON \
    -DWITH_FFTW=OFF \
    -DWITH_PORTAUDIO=OFF -DWITH_ALSA=NO -DWITH_JACK=NO -DARCH=x86_64 \
    -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ \
    -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g" "$SRC_PATH"
