#!/bin/bash

GCC=gcc-5
GXX=g++-5
SRC_PATH="$(dirname $0)/../.."

echo $SRC_PATH
cmake -DWITH_COVERAGE=ON -DWITH_PORTMIDI=OFF -DWITH_DUMMY=ON \
    -DWITH_FFTW=OFF -DWITH_OSS=OFF \
    -DWITH_PORTAUDIO=OFF -DWITH_ALSA=OFF -DWITH_JACK=OFF -DARCH=x86_64 \
    -DCMAKE_C_COMPILER=${GCC} -DCMAKE_CXX_COMPILER=${GXX} \
    -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g" "$SRC_PATH"
