#!/bin/bash

set -e

if [ "$1" = "configure" ]; then
	ln -s /usr/lib/pd_ceammc/bin/pd /usr/bin/pd-ceammc
	ln -s /usr/lib/pd_ceammc/bin/pdsend  /usr/bin/pdsend-ceammc
	ln -s /usr/lib/pd_ceammc/bin/pdreceive /usr/bin/pdreceive-ceammc
	ldconfig
fi

