#![allow(dead_code)]

pub const CEAMMC_LIB_VERSION_MAJOR: u8 = @CEAMMC_LIB_VERSION_MAJOR@;
pub const CEAMMC_LIB_VERSION_MINOR: u8 = @CEAMMC_LIB_VERSION_MINOR@;
pub const CEAMMC_LIB_VERSION_PATCH: u8 = @CEAMMC_LIB_VERSION_PATCH@;
pub const CEAMMC_LIB_VERSION: &str = "@CEAMMC_LIB_VERSION@";
pub const CEAMMC_LIB_HOME: &str = "https://github.com/uliss/pd-ceammc";
pub const CEAMMC_DISTRIB_VERSION: &str = "@CEAMMC_DISTRIB_VERSION@";

pub const PD_MAJOR_VERSION: u8 = @PD_MAJOR_VERSION@;
pub const PD_MINOR_VERSION: u8 = @PD_MINOR_VERSION@;
pub const PD_BUGFIX_VERSION: u8 = @PD_BUGFIX_VERSION@;
pub const PD_BUILD_SUFFIX: &str = "ceammc";
pub const PD_TEXT_VERSION_SHORT: &str = "@PD_MAJOR_VERSION@.@PD_MINOR_VERSION@.@PD_BUGFIX_VERSION@";
pub const PD_TEXT_VERSION_FULL: &str = "@PD_TEXT_VERSION_SHORT@_@PD_BUILD_SUFFIX@";

pub const GIT_BRANCH: &str = "@GIT_BRANCH@";
pub const GIT_COMMIT: &str = "@GIT_COMMIT@";
