#include "mod_list.h"
#include "list_route.h"

void setup_list_all_of();
void setup_list_any_of();
void setup_list_append();
void setup_list_apply_to();
void setup_list_at();
void setup_list_choice();
void setup_list_contains();
void setup_list_count();
void setup_list_count_if();
void setup_list_delta();
void setup_list_distribution();
void setup_list_do();
void setup_list_each();
void setup_list_enumerate();
void setup_list_equal();
void setup_list_first();
void setup_list_gen();
void setup_list_histogram();
void setup_list_insert();
void setup_list_integrator();
void setup_list_last();
void setup_list_length();
void setup_list_max();
void setup_list_mean();
void setup_list_min();
void setup_list_none_of();
void setup_list_normalize();
void setup_list_pass_if();
void setup_list_prepend();
void setup_list_product();
void setup_list_range();
void setup_list_reduce();
void setup_list_remove();
void setup_list_remove_if();
void setup_list_repack();
void setup_list_repeat();
void setup_list_resample();
void setup_list_resize();
void setup_list_reverse();
void setup_list_rldecode();
void setup_list_rlencode();
void setup_list_rotate();
void setup_list_search();
void setup_list_separate();
void setup_list_seq();
void setup_list_set();
void setup_list_shift();
void setup_list_shuffle();
void setup_list_slice();
void setup_list_sort();
void setup_list_sort_with();
void setup_list_split();
void setup_list_stretch();
void setup_list_sum();
void setup_list_unique();
void setup_list_unpack();
void setup_list_unzip();
void setup_list_walk();
void setup_list_xat();
void setup_list_xcontains();
void setup_list_xsearch();
void setup_list_zip();

void ceammc_list_setup()
{
    setup_list_all_of();
    setup_list_any_of();
    setup_list_append();
    setup_list_apply_to();
    setup_list_at();
    setup_list_choice();
    setup_list_contains();
    setup_list_count();
    setup_list_count_if();
    setup_list_delta();
    setup_list_distribution();
    setup_list_do();
    setup_list_each();
    setup_list_enumerate();
    setup_list_equal();
    setup_list_first();
    setup_list_gen();
    setup_list_histogram();
    setup_list_insert();
    setup_list_integrator();
    setup_list_last();
    setup_list_length();
    setup_list_max();
    setup_list_mean();
    setup_list_min();
    setup_list_none_of();
    setup_list_normalize();
    setup_list_pass_if();
    setup_list_prepend();
    setup_list_product();
    setup_list_range();
    setup_list_reduce();
    setup_list_remove();
    setup_list_remove_if();
    setup_list_repack();
    setup_list_repeat();
    setup_list_resample();
    setup_list_resize();
    setup_list_reverse();
    setup_list_rldecode();
    setup_list_rlencode();
    setup_list_rotate();
    setup_list_route();
    setup_list_search();
    setup_list_separate();
    setup_list_seq();
    setup_list_set();
    setup_list_shift();
    setup_list_shuffle();
    setup_list_slice();
    setup_list_sort();
    setup_list_sort_with();
    setup_list_split();
    setup_list_stretch();
    setup_list_sum();
    setup_list_unique();
    setup_list_unpack();
    setup_list_unzip();
    setup_list_walk();
    setup_list_xat();
    setup_list_xcontains();
    setup_list_xsearch();
    setup_list_zip();
}
