[package]
name = "ceammc_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rhvoice_download"
path = "src/rhvoice_download/main.rs"

[[bin]] 
name = "dylibfix"
path = "src/dylibfix/main.rs"

[[bin]] 
name = "ceam"
path = "src/ceam/main.rs"
 
[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
colored = "3.1.1"
env_logger = "0.11.9"
exitcode = "1.1.2"
homedir = "0.3.6"
indicatif = "0.18.4"
log = "0.4.29"
mach_object = "0.1.17"
memmap = "0.7.0"
octocrab = "0.38.0"
reqwest = "0.13.2"
tempfile = "3.25.0"
tokio = { version = "1.37.0", features = ["macros"] }
zip = "1.1.4"

[profile.release]
strip = true
