var dir_13ee4f635c0c81055866b45db81d92cb =
[
    [ "utf8rewind", "dir_72b9ca800ac319359de516ffda48565d.html", "dir_72b9ca800ac319359de516ffda48565d" ],
    [ "array_load_pattern.cpp", "array__load__pattern_8cpp.html", "array__load__pattern_8cpp" ],
    [ "array_load_pattern.h", "array__load__pattern_8h.html", "array__load__pattern_8h" ],
    [ "ceammc.c", "ceammc_8c.html", "ceammc_8c" ],
    [ "ceammc.cpp", "ceammc_8cpp.html", "ceammc_8cpp" ],
    [ "ceammc.h", "ceammc_8h.html", "ceammc_8h" ],
    [ "ceammc.hpp", "ceammc_8hpp.html", "ceammc_8hpp" ],
    [ "ceammc_abstractdata.cpp", "ceammc__abstractdata_8cpp.html", null ],
    [ "ceammc_abstractdata.h", "ceammc__abstractdata_8h.html", [
      [ "AbstractData", "classceammc_1_1_abstract_data.html", "classceammc_1_1_abstract_data" ]
    ] ],
    [ "ceammc_array.cpp", "ceammc__array_8cpp.html", "ceammc__array_8cpp" ],
    [ "ceammc_array.h", "ceammc__array_8h.html", "ceammc__array_8h" ],
    [ "ceammc_atom.cpp", "ceammc__atom_8cpp.html", "ceammc__atom_8cpp" ],
    [ "ceammc_atom.h", "ceammc__atom_8h.html", "ceammc__atom_8h" ],
    [ "ceammc_atomlist.cpp", "ceammc__atomlist_8cpp.html", "ceammc__atomlist_8cpp" ],
    [ "ceammc_atomlist.h", "ceammc__atomlist_8h.html", "ceammc__atomlist_8h" ],
    [ "ceammc_autopreset.cpp", "ceammc__autopreset_8cpp.html", "ceammc__autopreset_8cpp" ],
    [ "ceammc_autopreset.h", "ceammc__autopreset_8h.html", "ceammc__autopreset_8h" ],
    [ "ceammc_bpf.h", "ceammc__bpf_8h.html", "ceammc__bpf_8h" ],
    [ "ceammc_canvas.cpp", "ceammc__canvas_8cpp.html", "ceammc__canvas_8cpp" ],
    [ "ceammc_canvas.h", "ceammc__canvas_8h.html", "ceammc__canvas_8h" ],
    [ "ceammc_convert.cpp", "ceammc__convert_8cpp.html", [
      [ "TimeFSM", "class_time_f_s_m.html", "class_time_f_s_m" ]
    ] ],
    [ "ceammc_convert.h", "ceammc__convert_8h.html", "ceammc__convert_8h" ],
    [ "ceammc_convert_pitch.cpp", "ceammc__convert__pitch_8cpp.html", "ceammc__convert__pitch_8cpp" ],
    [ "ceammc_data.cpp", "ceammc__data_8cpp.html", null ],
    [ "ceammc_data.h", "ceammc__data_8h.html", "ceammc__data_8h" ],
    [ "ceammc_dataatom.cpp", "ceammc__dataatom_8cpp.html", "ceammc__dataatom_8cpp" ],
    [ "ceammc_dataatom.h", "ceammc__dataatom_8h.html", "ceammc__dataatom_8h" ],
    [ "ceammc_dataatomlist.cpp", "ceammc__dataatomlist_8cpp.html", "ceammc__dataatomlist_8cpp" ],
    [ "ceammc_dataatomlist.h", "ceammc__dataatomlist_8h.html", "ceammc__dataatomlist_8h" ],
    [ "ceammc_datastorage.cpp", "ceammc__datastorage_8cpp.html", null ],
    [ "ceammc_datastorage.h", "ceammc__datastorage_8h.html", "ceammc__datastorage_8h" ],
    [ "ceammc_datatypes.h", "ceammc__datatypes_8h.html", null ],
    [ "ceammc_factory.cpp", "ceammc__factory_8cpp.html", null ],
    [ "ceammc_factory.h", "ceammc__factory_8h.html", "ceammc__factory_8h" ],
    [ "ceammc_faust.cpp", "ceammc__faust_8cpp.html", "ceammc__faust_8cpp" ],
    [ "ceammc_faust.h", "ceammc__faust_8h.html", "ceammc__faust_8h" ],
    [ "ceammc_fn_list.cpp", "ceammc__fn__list_8cpp.html", "ceammc__fn__list_8cpp" ],
    [ "ceammc_fn_list.h", "ceammc__fn__list_8h.html", "ceammc__fn__list_8h" ],
    [ "ceammc_fn_vector.cpp", "ceammc__fn__vector_8cpp.html", "ceammc__fn__vector_8cpp" ],
    [ "ceammc_fn_vector.h", "ceammc__fn__vector_8h.html", "ceammc__fn__vector_8h" ],
    [ "ceammc_format.cpp", "ceammc__format_8cpp.html", "ceammc__format_8cpp" ],
    [ "ceammc_format.h", "ceammc__format_8h.html", "ceammc__format_8h" ],
    [ "ceammc_globaldata.h", "ceammc__globaldata_8h.html", [
      [ "NamedDataDict", "classceammc_1_1_named_data_dict.html", "classceammc_1_1_named_data_dict" ],
      [ "GlobalData", "classceammc_1_1_global_data.html", "classceammc_1_1_global_data" ]
    ] ],
    [ "ceammc_gui.h", "ceammc__gui_8h.html", "ceammc__gui_8h" ],
    [ "ceammc_impl.cpp", "ceammc__impl_8cpp.html", "ceammc__impl_8cpp" ],
    [ "ceammc_impl.h", "ceammc__impl_8h.html", "ceammc__impl_8h" ],
    [ "ceammc_loader_coreaudio.cpp", "ceammc__loader__coreaudio_8cpp.html", null ],
    [ "ceammc_loader_coreaudio.h", "ceammc__loader__coreaudio_8h.html", [
      [ "CoreAudioFile", "classceammc_1_1sound_1_1_core_audio_file.html", "classceammc_1_1sound_1_1_core_audio_file" ]
    ] ],
    [ "ceammc_loader_coreaudio_impl.h", "ceammc__loader__coreaudio__impl_8h.html", "ceammc__loader__coreaudio__impl_8h" ],
    [ "ceammc_loader_coreaudio_impl.m", "ceammc__loader__coreaudio__impl_8m.html", "ceammc__loader__coreaudio__impl_8m" ],
    [ "ceammc_loader_sndfile.cpp", "ceammc__loader__sndfile_8cpp.html", null ],
    [ "ceammc_loader_sndfile.h", "ceammc__loader__sndfile_8h.html", [
      [ "LibSndFile", "classceammc_1_1sound_1_1_lib_snd_file.html", "classceammc_1_1sound_1_1_lib_snd_file" ]
    ] ],
    [ "ceammc_log.cpp", "ceammc__log_8cpp.html", "ceammc__log_8cpp" ],
    [ "ceammc_log.h", "ceammc__log_8h.html", "ceammc__log_8h" ],
    [ "ceammc_message.cpp", "ceammc__message_8cpp.html", "ceammc__message_8cpp" ],
    [ "ceammc_message.h", "ceammc__message_8h.html", "ceammc__message_8h" ],
    [ "ceammc_music_theory.cpp", "ceammc__music__theory_8cpp.html", null ],
    [ "ceammc_music_theory.h", "ceammc__music__theory_8h.html", "ceammc__music__theory_8h" ],
    [ "ceammc_music_theory_alteration.cpp", "ceammc__music__theory__alteration_8cpp.html", null ],
    [ "ceammc_music_theory_alteration.h", "ceammc__music__theory__alteration_8h.html", "ceammc__music__theory__alteration_8h" ],
    [ "ceammc_music_theory_names.cpp", "ceammc__music__theory__names_8cpp.html", null ],
    [ "ceammc_music_theory_names.h", "ceammc__music__theory__names_8h.html", "ceammc__music__theory__names_8h" ],
    [ "ceammc_music_theory_pitch_class.cpp", "ceammc__music__theory__pitch__class_8cpp.html", null ],
    [ "ceammc_music_theory_pitch_class.h", "ceammc__music__theory__pitch__class_8h.html", "ceammc__music__theory__pitch__class_8h" ],
    [ "ceammc_music_theory_pitch_name.cpp", "ceammc__music__theory__pitch__name_8cpp.html", null ],
    [ "ceammc_music_theory_pitch_name.h", "ceammc__music__theory__pitch__name_8h.html", "ceammc__music__theory__pitch__name_8h" ],
    [ "ceammc_object.cpp", "ceammc__object_8cpp.html", "ceammc__object_8cpp" ],
    [ "ceammc_object.h", "ceammc__object_8h.html", [
      [ "PdArgs", "classceammc_1_1_pd_args.html", "classceammc_1_1_pd_args" ],
      [ "BaseObject", "classceammc_1_1_base_object.html", "classceammc_1_1_base_object" ],
      [ "SoundExternal", "classceammc_1_1_sound_external.html", "classceammc_1_1_sound_external" ]
    ] ],
    [ "ceammc_pd.cpp", "ceammc__pd_8cpp.html", "ceammc__pd_8cpp" ],
    [ "ceammc_pd.h", "ceammc__pd_8h.html", "ceammc__pd_8h" ],
    [ "ceammc_platform.cpp", "ceammc__platform_8cpp.html", "ceammc__platform_8cpp" ],
    [ "ceammc_platform.h", "ceammc__platform_8h.html", "ceammc__platform_8h" ],
    [ "ceammc_platform_unix.cpp", "ceammc__platform__unix_8cpp.html", null ],
    [ "ceammc_platform_unix.h", "ceammc__platform__unix_8h.html", "ceammc__platform__unix_8h" ],
    [ "ceammc_platform_win.cpp", "ceammc__platform__win_8cpp.html", "ceammc__platform__win_8cpp" ],
    [ "ceammc_platform_win.h", "ceammc__platform__win_8h.html", "ceammc__platform__win_8h" ],
    [ "ceammc_property.cpp", "ceammc__property_8cpp.html", null ],
    [ "ceammc_property.h", "ceammc__property_8h.html", "ceammc__property_8h" ],
    [ "ceammc_proxy.h", "ceammc__proxy_8h.html", [
      [ "PdProxy", "structceammc_1_1_pd_proxy.html", "structceammc_1_1_pd_proxy" ],
      [ "PdFloatProxy", "structceammc_1_1_pd_float_proxy.html", "structceammc_1_1_pd_float_proxy" ]
    ] ],
    [ "ceammc_sound.cpp", "ceammc__sound_8cpp.html", null ],
    [ "ceammc_sound.h", "ceammc__sound_8h.html", "ceammc__sound_8h" ],
    [ "ceammc_string.cpp", "ceammc__string_8cpp.html", null ],
    [ "ceammc_string.h", "ceammc__string_8h.html", "ceammc__string_8h" ],
    [ "ceammc_timeline.cpp", "ceammc__timeline_8cpp.html", "ceammc__timeline_8cpp" ],
    [ "ceammc_timeline.h", "ceammc__timeline_8h.html", "ceammc__timeline_8h" ],
    [ "ceammc_window.cpp", "ceammc__window_8cpp.html", null ],
    [ "ceammc_window.h", "ceammc__window_8h.html", "ceammc__window_8h" ],
    [ "ext_list.cpp", "ext__list_8cpp.html", "ext__list_8cpp" ],
    [ "memrss.h", "memrss_8h.html", "memrss_8h" ],
    [ "memsize.h", "memsize_8h.html", "memsize_8h" ]
];