// this is autogenerated file, do not edit!
#ifndef midi_kdb_querty_h_
#define midi_kdb_querty_h_
#include <unordered_map>
#include <cstdint>
static std::unordered_map<uint32_t, uint8_t> kdb_querty = {
    { 44, 12 }, // ","
    { 46, 14 }, // "."
    { 59, 15 }, // ";"
    { 98, 7 }, // "b"
    { 99, 4 }, // "c"
    { 100, 3 }, // "d"
    { 103, 6 }, // "g"
    { 104, 8 }, // "h"
    { 106, 10 }, // "j"
    { 108, 13 }, // "l"
    { 109, 11 }, // "m"
    { 110, 9 }, // "n"
    { 115, 1 }, // "s"
    { 118, 5 }, // "v"
    { 120, 2 }, // "x"
    { 122, 0 }, // "z"
};
#endif // midi_kdb_querty_h_
