#!/bin/bash
#

cmake -DCMAKE_INSTALL_PREFIX=~/.local/faust \
	-DCMAKE_BUILD_TYPE=Release \
	-DLLVM_BACKEND='STATIC DYNAMIC' \
	-DC_BACKEND='STATIC DYNAMIC' \
	-DCPP_BACKEND='STATIC DYNAMIC' \
	-DINCLUDE_EMCC=OFF \
	-DINCLUDE_OSC=OFF \
	-DINCLUDE_HTTP=OFF \
	-DINCLUDE_WASM_GLUE=OFF \
	-DINCLUDE_STATIC=OFF \
	-DINCLUDE_DYNAMIC=ON \
	-DINCLUDE_EXECUTABLE=OFF \
	-DSELF_CONTAINED_LIBRARY=ON \
	.

cmake -L
