#define TK_FLOAT                            1
#define TK_SYMBOL                           2
#define TK_NULL                             3
#define TK_STRING                           4
#define TK_DICT_KEY                         5
#define TK_LIST_OPEN                        6
#define TK_LIST_CLOSE                       7
#define TK_DATA_NAME                        8
#define TK_DICT_OPEN                        9
#define TK_DICT_CLOSE                      10
#define TK_SPACE                           11
#define TK_MATRIX                          12
#define TK_MATRIX_CLOSE                    13
#define TK_FUNC_LIST_CALL                  14
