// select.lexer.cpp generated by reflex 1.6.3 from select.l

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_YYLTYPE             ceammc::location
#define REFLEX_OPTION_YYSTYPE             ceammc::SelectParser::semantic_type
#define REFLEX_OPTION_bison_cc            true
#define REFLEX_OPTION_bison_cc_namespace  ceammc
#define REFLEX_OPTION_bison_cc_parser     SelectParser
#define REFLEX_OPTION_bison_complete      true
#define REFLEX_OPTION_freespace           true
#define REFLEX_OPTION_header_file         "select.lexer.h"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               SelectLexer
#define REFLEX_OPTION_namespace           ceammc
#define REFLEX_OPTION_noindent            true
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "select.lexer.cpp"
#define REFLEX_OPTION_reentrant           true
#define REFLEX_OPTION_token_eof           ceammc::SelectParser::symbol_type(0)
#define REFLEX_OPTION_token_type          ceammc::SelectParser::symbol_type
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top{ user code %}                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 1 "select.l"

    # include <string>
    # include <array>
    # include <stdexcept>

    # include "lex/select.parser.hpp"

    using token = ceammc::SelectParser::token;


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define WITH_NO_INDENT
#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace ceammc {

class SelectLexer : public reflex::AbstractLexer<reflex::Matcher> {
#line 11 "select.l"

    public:
        enum MatchType {
            MATCH_EQUAL,
            MATCH_EPSILON,
            MATCH_RANGE_OO,
            MATCH_RANGE_CC,
            MATCH_RANGE_OC,
            MATCH_RANGE_CO,
            MATCH_SET,
            MATCH_LESS,
            MATCH_LESS_EQ,
            MATCH_GREATER,
            MATCH_GREATER_EQ
        };

        struct LexerAtom {
            std::string txt;
            bool is_float;
        };

        struct MatchData {
            ceammc::Atom atoms[16];
            size_t natoms = { 0 };
            MatchType type = { MATCH_EQUAL };

            MatchData(){}

            MatchData(double v) : natoms(1), type(MATCH_EQUAL) {
                atoms[0].setFloat(v, true);
            }

            MatchData(const std::string& s) : natoms(1), type(MATCH_EQUAL) {
                atoms[0].setSymbol(gensym(s.c_str()), true);
            }

            static MatchData epsilon(double a, double b) {
                MatchData res;
                res.natoms = 2;
                res.type = MATCH_EPSILON;
                res.atoms[0].setFloat(a, true);
                res.atoms[1].setFloat(b, true);
                return res;
            }

            static MatchData range(double a, double b, MatchType t) {
                MatchData res;
                res.natoms = 2;
                res.type = t;
                res.atoms[0].setFloat(a, true);
                res.atoms[1].setFloat(b, true);
                return res;
            }

            static MatchData compare(double x, MatchType t) {
                MatchData res;
                res.natoms = 1;
                res.type = t;
                res.atoms[0].setFloat(x, true);
                return res;
            }
        };

        void pushMatch(const MatchData& d)
        {
            if(nmatches_ < matches_.size())
                matches_[nmatches_++] = d;
        }

        void pushLexerAtom(const LexerAtom& a)
        {
            atoms_.push_back(a);
        }

        void popLexerAtoms()
        {
            if(atoms_.size() == 1 && atoms_[0].is_float)
                pushMatch(MatchData(std::strtod(atoms_[0].txt.c_str(), nullptr)));
            else {
                std::string res;
                for(auto& a: atoms_)
                    res += a.txt;

                pushMatch(MatchData(res));
            }

            atoms_.clear();
        }

        const MatchData& operator[](size_t idx) const {
            if(idx >= nmatches_)
                throw std::out_of_range("invalid index");

            return matches_[idx];
        }

        size_t numMatches() const { return nmatches_; }
        void clearMatches() { nmatches_ = 0; }
        void mergeMatch() {
            if(nmatches_ < 2)
                return;

            auto& m0 = matches_[nmatches_-2];
            const auto& m1 = matches_[nmatches_-1];
            for(size_t i = 0; i < m1.natoms; i++)
                m0.atoms[m0.natoms++] = m1.atoms[i];


            m0.type = MATCH_SET;
            nmatches_ -= 1;
        }

        void setErrorMsg(const std::string& str) { error_msg_ = str; }

    private:
        std::array<MatchData, 64> matches_;
        std::vector<LexerAtom> atoms_;
        size_t nmatches_ = {0};
        std::string error_msg_;

 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  SelectLexer(
      const reflex::Input& input = reflex::Input(),
      std::ostream&        os    = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  static const int RANGE = 1;
  static const int EPSILON = 2;
  virtual ceammc::SelectParser::symbol_type lex(void);
};

} // namespace ceammc

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 137 "select.l"
/*%option graphs-file*/
/*%option debug*/
/*%option perf-report*/
#line 147 "select.l"
/*%option fast*/


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  BISON C++                                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

ceammc::SelectParser::symbol_type ceammc::SelectLexer::lex()
{
  static const char *REGEX_INITIAL = "(?mx)((?:[\\x09\\x0a\\x20]+))|((?:~)(?=(?:(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?)))|((?:\\.\\.)(?=(?:(?:[\\x2b\\x2d]?(?:0|[1-9][0-9]*))(?:\\.[0-9]+)?)))|((?:\\[)(?=(?:(?:[\\x2b\\x2d]?(?:0|[1-9][0-9]*))(?:\\.[0-9]+)?)))|((?:\\]))|((?:\\()(?=(?:(?:[\\x2b\\x2d]?(?:0|[1-9][0-9]*))(?:\\.[0-9]+)?)))|((?:\\)))|((?:\\|))|((?:>=)(?=(?:(?:[\\x2b\\x2d]?(?:0|[1-9][0-9]*))(?:\\.[0-9]+)?)))|((?:>)(?=(?:(?:[\\x2b\\x2d]?(?:0|[1-9][0-9]*))(?:\\.[0-9]+)?)))|((?:<)(?=(?:(?:[\\x2b\\x2d]?(?:0|[1-9][0-9]*))(?:\\.[0-9]+)?)))|((?:<=)(?=(?:(?:[\\x2b\\x2d]?(?:0|[1-9][0-9]*))(?:\\.[0-9]+)?)))|((?:(?:[\\x2b\\x2d]?(?:0|[1-9][0-9]*))(?:\\.[0-9]+)?))|((?:(?:[\\x00-\\x08]|[\\x0b-\\x1f]|[!-/]|[:-{]|[}-\\x7f]|[\\xc2-\\xdf][\\x80-\\xbf]|\\xe0[\\xa0-\\xbf][\\x80-\\xbf]|[\\xe1-\\xec][\\x80-\\xbf][\\x80-\\xbf]|\\xed[\\x80-\\x9f][\\x80-\\xbf]|[\\xee\\xef][\\x80-\\xbf][\\x80-\\xbf]|\\xf0[\\x90-\\xbf][\\x80-\\xbf][\\x80-\\xbf]|[\\xf1-\\xf3][\\x80-\\xbf][\\x80-\\xbf][\\x80-\\xbf]|\\xf4[\\x80-\\x8f][\\x80-\\xbf][\\x80-\\xbf])+))|(.)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  static const char *REGEX_RANGE = "(?mx)(.)";
  static const reflex::Pattern PATTERN_RANGE(REGEX_RANGE);
  static const char *REGEX_EPSILON = "(?mx)(.)";
  static const reflex::Pattern PATTERN_EPSILON(REGEX_EPSILON);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
    switch (start())
    {
      case INITIAL:
        matcher().pattern(PATTERN_INITIAL);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return ceammc::SelectParser::symbol_type(0);
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 178: (?:[\x09\x0a\x20]+)
#line 178 "select.l"
{ return SelectParser::make_SPACE(); }
            break;
          case 2: // rule at line 179: (?:~)(?=(?:(?:0|[1-9][0-9]*)(?:\.[0-9]+)?))
#line 179 "select.l"
{ return SelectParser::make_EPSILON(); }
            break;
          case 3: // rule at line 180: (?:\.\.)(?=(?:(?:[\x2b\x2d]?(?:0|[1-9][0-9]*))(?:\.[0-9]+)?))
#line 180 "select.l"
{ return SelectParser::make_RANGE(); }
            break;
          case 4: // rule at line 181: (?:\[)(?=(?:(?:[\x2b\x2d]?(?:0|[1-9][0-9]*))(?:\.[0-9]+)?))
#line 181 "select.l"
{ return SelectParser::make_OPEN_BRACKET('['); }
            break;
          case 5: // rule at line 182: (?:\])
#line 182 "select.l"
{ return SelectParser::make_CLOSE_BRACKET(']'); }
            break;
          case 6: // rule at line 183: (?:\()(?=(?:(?:[\x2b\x2d]?(?:0|[1-9][0-9]*))(?:\.[0-9]+)?))
#line 183 "select.l"
{ return SelectParser::make_OPEN_PAR('('); }
            break;
          case 7: // rule at line 184: (?:\))
#line 184 "select.l"
{ return SelectParser::make_CLOSE_PAR(')'); }
            break;
          case 8: // rule at line 185: (?:\|)
#line 185 "select.l"
{ return SelectParser::make_OR(); }
            break;
          case 9: // rule at line 186: (?:>=)(?=(?:(?:[\x2b\x2d]?(?:0|[1-9][0-9]*))(?:\.[0-9]+)?))
#line 186 "select.l"
{ return SelectParser::make_OP_GREATER_EQ(); }
            break;
          case 10: // rule at line 187: (?:>)(?=(?:(?:[\x2b\x2d]?(?:0|[1-9][0-9]*))(?:\.[0-9]+)?))
#line 187 "select.l"
{ return SelectParser::make_OP_GREATER(); }
            break;
          case 11: // rule at line 188: (?:<)(?=(?:(?:[\x2b\x2d]?(?:0|[1-9][0-9]*))(?:\.[0-9]+)?))
#line 188 "select.l"
{ return SelectParser::make_OP_LESS(); }
            break;
          case 12: // rule at line 189: (?:<=)(?=(?:(?:[\x2b\x2d]?(?:0|[1-9][0-9]*))(?:\.[0-9]+)?))
#line 189 "select.l"
{ return SelectParser::make_OP_LESS_EQ(); }
            break;
          case 13: // rule at line 190: (?:(?:[\x2b\x2d]?(?:0|[1-9][0-9]*))(?:\.[0-9]+)?)
#line 190 "select.l"
{ return SelectParser::make_FLOAT(text()); }
            break;
          case 14: // rule at line 192: (?:(?:[\x00-\x08]|[\x0b-\x1f]|[!-/]|[:-{]|[}-\x7f]|[\xc2-\xdf][\x80-\xbf]|\xe0[\xa0-\xbf][\x80-\xbf]|[\xe1-\xec][\x80-\xbf][\x80-\xbf]|\xed[\x80-\x9f][\x80-\xbf]|[\xee\xef][\x80-\xbf][\x80-\xbf]|\xf0[\x90-\xbf][\x80-\xbf][\x80-\xbf]|[\xf1-\xf3][\x80-\xbf][\x80-\xbf][\x80-\xbf]|\xf4[\x80-\x8f][\x80-\xbf][\x80-\xbf])+)
#line 192 "select.l"
{ return SelectParser::make_SYMBOL(text()); }

            break;
          case 15: // rule at line 194: .
#line 194 "select.l"
{   }

            break;
        }
        break;
      case RANGE:
        matcher().pattern(PATTERN_RANGE);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return ceammc::SelectParser::symbol_type(0);
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 194: .
#line 194 "select.l"
{   }

            break;
        }
        break;
      case EPSILON:
        matcher().pattern(PATTERN_EPSILON);
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return ceammc::SelectParser::symbol_type(0);
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule at line 194: .
#line 194 "select.l"
{   }

            break;
        }
        break;
      default:
        start(0);
    }
  }
}
