#include "mod_flt.h"

void setup_flt_a_weight();
void setup_flt_apf2biquad();
void setup_flt_biquad_tilde();
void setup_flt_bpf12_tilde();
void setup_flt_bpf24_tilde();
void setup_flt_c_bpf_tilde();
void setup_flt_c_highshelf_tilde();
void setup_flt_c_hpf_tilde();
void setup_flt_c_lowshelf_tilde();
void setup_flt_c_lpf_tilde();
void setup_flt_c_notch();
void setup_flt_c_notch_tilde();
void setup_flt_c_peak_tilde();
void setup_flt_dcblock2_tilde();
void setup_flt_dcblock_tilde();
void setup_flt_eq10_tilde();
void setup_flt_eq_peak_cq_tilde();
void setup_flt_eq_peak_tilde();
void setup_flt_fb_comb_tilde();
void setup_flt_ff_comb_tilde();
void setup_flt_filterbank5x1_tilde();
void setup_flt_freqz();
void setup_flt_freqz_tilde();
void setup_flt_highshelf_tilde();
void setup_flt_hpf12_tilde();
void setup_flt_hpf24_tilde();
void setup_flt_hpf2biquad();
void setup_flt_lowshelf_tilde();
void setup_flt_lpf12_tilde();
void setup_flt_lpf24_tilde();
void setup_flt_lpf2biquad();
void setup_flt_median();
void setup_flt_moog_vcf_tilde();
void setup_flt_notch_tilde();
void setup_flt_pole2biquad();
void setup_flt_resonbp_tilde();
void setup_flt_resonhp_tilde();
void setup_flt_resonlp_tilde();
void setup_flt_speaker_tilde();

void ceammc_flt_setup()
{
    setup_flt_a_weight();
    setup_flt_apf2biquad();
    setup_flt_biquad_tilde();
    setup_flt_bpf12_tilde();
    setup_flt_bpf24_tilde();
    setup_flt_c_bpf_tilde();
    setup_flt_c_highshelf_tilde();
    setup_flt_c_hpf_tilde();
    setup_flt_c_lowshelf_tilde();
    setup_flt_c_lpf_tilde();
    setup_flt_c_notch();
    setup_flt_c_notch_tilde();
    setup_flt_c_peak_tilde();
    setup_flt_dcblock2_tilde();
    setup_flt_dcblock_tilde();
    setup_flt_eq10_tilde();
    setup_flt_eq_peak_cq_tilde();
    setup_flt_eq_peak_tilde();
    setup_flt_fb_comb_tilde();
    setup_flt_ff_comb_tilde();
    setup_flt_filterbank5x1_tilde();
    setup_flt_freqz();
    setup_flt_freqz_tilde();
    setup_flt_highshelf_tilde();
    setup_flt_hpf12_tilde();
    setup_flt_hpf24_tilde();
    setup_flt_hpf2biquad();
    setup_flt_lowshelf_tilde();
    setup_flt_lpf12_tilde();
    setup_flt_lpf24_tilde();
    setup_flt_lpf2biquad();
    setup_flt_median();
    setup_flt_moog_vcf_tilde();
    setup_flt_notch_tilde();
    setup_flt_pole2biquad();
    setup_flt_resonbp_tilde();
    setup_flt_resonhp_tilde();
    setup_flt_resonlp_tilde();
    setup_flt_speaker_tilde();
}
