// this is autogenerated file, do not edit!
#ifndef FRAME_H_
#define FRAME_H_
// clang-format off

#include "nui/model.h"
#include "nui/style.h"
#include "m_pd.h"

#include <tuple>

namespace ceammc {
namespace ui {

enum FrameDataFields {
    FRAME_DATA_SIZE,
    FRAME_DATA_BORDER_COLOR,
    FRAME_DATA_FILL_COLOR,
    FRAME_DATA_PADDING,
    FRAME_DATA_SELECTED,
    FRAME_DATA_STYLE_IDX,
};

class FrameData
    : public std::tuple<Size, HexColor, HexColor, int, bool, int> {
public:
    FrameData()
        : std::tuple<Size, HexColor, HexColor, int, bool, int>(Size(10, 10), colors::st_border, colors::st_fill, 5, false, 0) { }

    FrameData(int style)
        : FrameData() {
        setStyle(style);
        loadStyle(style);
    }

    // constants
    static HexColor selectColor() noexcept { return colors::blue; }
    static Size minSize() noexcept { return Size(1, 1); }

    // getters
    Size size() const noexcept { return std::get<FRAME_DATA_SIZE>(*this); }
    HexColor borderColor() const noexcept { return std::get<FRAME_DATA_BORDER_COLOR>(*this); }
    HexColor fillColor() const noexcept { return std::get<FRAME_DATA_FILL_COLOR>(*this); }
    int padding() const noexcept { return std::get<FRAME_DATA_PADDING>(*this); }
    bool selected() const noexcept { return std::get<FRAME_DATA_SELECTED>(*this); }
    int style() const noexcept { return std::get<FRAME_DATA_STYLE_IDX>(*this); }

    // setters
    void setSize(Size v) { std::get<FRAME_DATA_SIZE>(*this) = v; }
    void setBorderColor(HexColor v) { std::get<FRAME_DATA_BORDER_COLOR>(*this) = v; }
    void setFillColor(HexColor v) { std::get<FRAME_DATA_FILL_COLOR>(*this) = v; }
    void setPadding(int v) { std::get<FRAME_DATA_PADDING>(*this) = v; }
    void setSelected(bool v) { std::get<FRAME_DATA_SELECTED>(*this) = v; }
    void setStyle(int v) { std::get<FRAME_DATA_STYLE_IDX>(*this) = v; }

    // style
    void loadStyle(int st) {
        using sc = StyleCollection;
        setBorderColor(sc::color(st, "frame:border_color"_hash, colors::st_border));
        setFillColor(sc::color(st, "frame:fill_color"_hash, colors::st_fill));
    }
};

using FrameModel = ModelBase<FrameData>;

}
}

// clang-format on
#endif
