// this is autogenerated file, do not edit!
#ifndef FRAME_H_
#define FRAME_H_
// clang-format off

#include "nui/model.h"
#include "nui/style.h"
#include "m_pd.h"

#include <tuple>

namespace ceammc {
namespace ui {

class FrameData
    : public std::tuple<Size, HexColor, HexColor, int, bool, int> {
public:
    enum Fields {
        SIZE,
        BORDER_COLOR,
        FILL_COLOR,
        PADDING,
        SELECTED,
        STYLE_IDX,
    };
public:
    FrameData()
        : std::tuple<Size, HexColor, HexColor, int, bool, int>(Size(10, 10), colors::st_border, colors::st_fill, 5, false, 0) { }

    FrameData(int style)
        : FrameData() {
        setStyle(style);
        loadStyle(style);
    }

    // constants
    static HexColor selectColor() noexcept { return colors::blue; }

    // getters
    Size const& size() const noexcept { return std::get<SIZE>(*this); }
    HexColor const& borderColor() const noexcept { return std::get<BORDER_COLOR>(*this); }
    HexColor const& fillColor() const noexcept { return std::get<FILL_COLOR>(*this); }
    int const& padding() const noexcept { return std::get<PADDING>(*this); }
    bool const& selected() const noexcept { return std::get<SELECTED>(*this); }
    int const& style() const noexcept { return std::get<STYLE_IDX>(*this); }

    // setters
    void setSize(Size v) { std::get<SIZE>(*this) = v; }
    void setBorderColor(HexColor v) { std::get<BORDER_COLOR>(*this) = v; }
    void setFillColor(HexColor v) { std::get<FILL_COLOR>(*this) = v; }
    void setPadding(int v) { std::get<PADDING>(*this) = v; }
    void setSelected(bool v) { std::get<SELECTED>(*this) = v; }
    void setStyle(int v) { std::get<STYLE_IDX>(*this) = v; }

    // refs
    Size& sizeRef() { return std::get<SIZE>(*this); }
    HexColor& borderColorRef() { return std::get<BORDER_COLOR>(*this); }
    HexColor& fillColorRef() { return std::get<FILL_COLOR>(*this); }
    int& paddingRef() { return std::get<PADDING>(*this); }
    bool& selectedRef() { return std::get<SELECTED>(*this); }
    int& styleRef() { return std::get<STYLE_IDX>(*this); }

    // style
    void loadStyle(int st) {
        using sc = StyleCollection;
        setBorderColor(sc::color(st, "frame:border_color"_hash, colors::st_border));
        setFillColor(sc::color(st, "frame:fill_color"_hash, colors::st_fill));
    }
};

using FrameModel = ModelBase<FrameData>;

}
}

// clang-format on
#endif
