// this is autogenerated file, do not edit!
#ifndef SLIDER_H_
#define SLIDER_H_
// clang-format off

#include "nui/model.h"
#include "nui/style.h"
#include "m_pd.h"

#include <tuple>

namespace ceammc {
namespace ui {

class SliderData
    : public std::tuple<Size, t_float, t_float, t_float, HexColor, HexColor, HexColor, bool, int> {
public:
    enum Fields {
        SIZE,
        VALUE,
        MIN,
        MAX,
        BORDER_COLOR,
        FILL_COLOR,
        KNOB_COLOR,
        LOG_SCALE,
        STYLE_IDX,
    };
public:
    SliderData()
        : std::tuple<Size, t_float, t_float, t_float, HexColor, HexColor, HexColor, bool, int>(Size(100, 15), 0, 0, 1, colors::st_border, colors::st_fill, colors::st_active, false, 0) { }

    SliderData(int style)
        : SliderData() {
        setStyle(style);
        loadStyle(style);
    }


    // getters
    Size const& size() const noexcept { return std::get<SIZE>(*this); }
    t_float const& value() const noexcept { return std::get<VALUE>(*this); }
    t_float const& min() const noexcept { return std::get<MIN>(*this); }
    t_float const& max() const noexcept { return std::get<MAX>(*this); }
    HexColor const& borderColor() const noexcept { return std::get<BORDER_COLOR>(*this); }
    HexColor const& fillColor() const noexcept { return std::get<FILL_COLOR>(*this); }
    HexColor const& knobColor() const noexcept { return std::get<KNOB_COLOR>(*this); }
    bool const& logScale() const noexcept { return std::get<LOG_SCALE>(*this); }
    int const& style() const noexcept { return std::get<STYLE_IDX>(*this); }

    // setters
    void setSize(Size v) { std::get<SIZE>(*this) = v; }
    void setValue(t_float v) { std::get<VALUE>(*this) = v; }
    void setMin(t_float v) { std::get<MIN>(*this) = v; }
    void setMax(t_float v) { std::get<MAX>(*this) = v; }
    void setBorderColor(HexColor v) { std::get<BORDER_COLOR>(*this) = v; }
    void setFillColor(HexColor v) { std::get<FILL_COLOR>(*this) = v; }
    void setKnobColor(HexColor v) { std::get<KNOB_COLOR>(*this) = v; }
    void setLogScale(bool v) { std::get<LOG_SCALE>(*this) = v; }
    void setStyle(int v) { std::get<STYLE_IDX>(*this) = v; }

    // refs
    Size& sizeRef() { return std::get<SIZE>(*this); }
    t_float& valueRef() { return std::get<VALUE>(*this); }
    t_float& minRef() { return std::get<MIN>(*this); }
    t_float& maxRef() { return std::get<MAX>(*this); }
    HexColor& borderColorRef() { return std::get<BORDER_COLOR>(*this); }
    HexColor& fillColorRef() { return std::get<FILL_COLOR>(*this); }
    HexColor& knobColorRef() { return std::get<KNOB_COLOR>(*this); }
    bool& logScaleRef() { return std::get<LOG_SCALE>(*this); }
    int& styleRef() { return std::get<STYLE_IDX>(*this); }

    // style
    void loadStyle(int st) {
        using sc = StyleCollection;
        setSize(sc::size(st, "slider:size"_hash, Size(100, 15)));
        setBorderColor(sc::color(st, "slider:border_color"_hash, colors::st_border));
        setFillColor(sc::color(st, "slider:fill_color"_hash, colors::st_fill));
        setKnobColor(sc::color(st, "slider:knob_color"_hash, colors::st_active));
    }
};

using SliderModel = ModelBase<SliderData>;

}
}

// clang-format on
#endif
