// this is autogenerated file: do not edit
// clang-format off
#ifndef tl_cue_fn_tcl_h_
#define tl_cue_fn_tcl_h_
const char* tl_cue_fn_tcl = 
"namespace eval ::ceammc::tl:: {\n"
"    variable receive_symbol\n"
"}\n"
"proc ::ceammc::tl::unbind {tag event script} {\n"
"    set bind {}\n"
"    foreach x [split [bind $tag $event] \\\"\\n\\\"] {\n"
"        if {$x != $script} {\n"
"            lappend bind $x\n"
"        }\n"
"    }\n"
"    bind $tag $event {}\n"
"    foreach x $bind {bind $tag $event $x}\n"
"}\n"
"proc ::ceammc::tl::update_line {win x y w h} {\n"
"    pdsend \"tl_cue_canvas_resize .update_line $win.c $x $y $w $h\"\n"
"}\n"
"proc ::ceammc::tl::startpolling {} {\n"
"    ::pdwindow::verbose 0 \"\\[ceammc\\] start tl.cue canvas resize polling...\\n\"\n"
"    bind PatchWindow <Configure> {+::ceammc::tl::update_line %W %x %y %w %h }\n"
"}\n"
"proc ::ceammc::tl::stoppolling {} {\n"
"    ::pdwindow::verbose 0 \"\\[ceammc\\] stop tl.cue canvas resize polling...\\n\"\n"
"    unbind PatchWindow <Configure> {::ceammc::tl::update_line %W %x %y %w %h }\n"
"}\n"
;
#endif
// clang-format on
