[package]
name = "ceammc_rs_msg"
version = "0.4.1"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
cbindgen = "0.28.0"

[dependencies]
log = "0.4.29"
tokio = { version = "1.42", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "fs",
    "macros",
] }
tokio-util = "0.7.18"
