#ifndef ceammc_rs_msg_h
#define ceammc_rs_msg_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>
#include <cstddef>


enum class ceammc_msg_level {
    Error,
    Post,
    Debug,
    Log,
};

/// notify pd caller from other threads
struct ceammc_msg_notify {
    /// pd subscriber id
    size_t id;
    /// non null!
    void (*cb)(size_t id);
};

/// notify pd caller from other threads
struct ceammc_msg_notify_int {
    /// pd subscriber id
    size_t id;
    /// non null!
    void (*cb)(size_t id, int32_t value);
};

struct ceammc_msg_cb {
    /// user data pointer
    void *user;
    /// pd callback: non null!
    void (*cb)(void *user, ceammc_msg_level level, const char *msg);
};

#endif  // ceammc_rs_msg_h
