#ifndef ceammc_rust_synth_h
#define ceammc_rust_synth_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>
#include <cstddef>


struct ceammc_synth_dx7_sysex {

};


extern "C" {

void ceammc_synth_dx7_sysex_free(ceammc_synth_dx7_sysex *dx7);

ceammc_synth_dx7_sysex *ceammc_synth_dx7_sysex_new();

}  // extern "C"

#endif  // ceammc_rust_synth_h
