#ifndef ceammc_rust_synth_h
#define ceammc_rust_synth_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>
#include <cstddef>


enum class ceammc_synth_msg_level {
    DEBUG,
    POST,
    ERROR,
};

struct ceammc_synth_dx7_sysex;

using ceammc_synth_dx7_main_cb = void(*)(void *user,
                                         const char *name,
                                         uint8_t algorithm_id,
                                         bool oscillator_key_sync,
                                         uint8_t feedback_level,
                                         uint8_t transpose);

using ceammc_synth_dx7_lfo_cb = void(*)(void *user,
                                        uint8_t lfo_speed,
                                        uint8_t lfo_delay,
                                        uint8_t lfo_pitch_mod_depth,
                                        uint8_t lfo_pitch_mod_sensitivity,
                                        uint8_t lfo_amplitude_mod_depth,
                                        uint8_t lfo_waveform,
                                        bool lfo_key_sync);

using ceammc_synth_dx7_env_cb = void(*)(void *user, uint8_t levels[4], uint8_t rates[4]);

using ceammc_synth_dx7_op_cb = void(*)(void *user,
                                       size_t index,
                                       const uint8_t *levels,
                                       const uint8_t *rates,
                                       uint8_t scaling_break_point,
                                       uint8_t scaling_left_depth,
                                       uint8_t scaling_right_depth,
                                       uint8_t scaling_left_curve,
                                       uint8_t scaling_right_curve,
                                       int8_t detune,
                                       uint8_t rate_scaling,
                                       uint8_t velocity_sensitivity,
                                       uint8_t modulation_sensitivity,
                                       uint8_t output_level,
                                       uint8_t is_fixed,
                                       uint8_t frequency_course,
                                       uint8_t frequency_fine);

struct ceammc_synth_msg_cb {
    /// nullable
    void *user;
    /// not NULL!
    void (*cb)(void*, ceammc_synth_msg_level, const char*);
};


extern "C" {

void ceammc_synth_dx7_sysex_free(ceammc_synth_dx7_sysex *dx7);

bool ceammc_synth_dx7_sysex_info(ceammc_synth_dx7_sysex *dx);

bool ceammc_synth_dx7_sysex_load(ceammc_synth_dx7_sysex *dx,
                                 uint8_t idx,
                                 void *user,
                                 ceammc_synth_dx7_main_cb main_cb,
                                 ceammc_synth_dx7_lfo_cb lfo_cb,
                                 ceammc_synth_dx7_env_cb env_cb,
                                 ceammc_synth_dx7_op_cb ops_cb);

ceammc_synth_dx7_sysex *ceammc_synth_dx7_sysex_new(ceammc_synth_msg_cb msg_cb);

bool ceammc_synth_dx7_sysex_read_file(ceammc_synth_dx7_sysex *dx, const char *file);

}  // extern "C"

#endif  // ceammc_rust_synth_h
