[package]
name = "hw_rust"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[workspace]
resolver = "2"
members = ["lib_macro"]

[features]
cups = ["dep:cups-sys"]

[dependencies]
c_str_macro = "1.0.3"
env_logger = "0.11.9"
gilrs = "0.10.5"
log = "0.4.29"
tokio = { version = "1.36", features = [
    "rt",
    "rt-multi-thread",
    "signal",
    "sync",
    "macros",
    "time",
] }
cups-sys = { version = "0.1.4", optional = true }
ndarray = "0.17.2"
rgb = "0.8.52"
palette = { version = "0.7.6", features = ["std", "approx"] }
embedded-graphics = "0.8.1"
embedded-hal = { version = "1.0.0", features = [] }
lib_macro = { path = "lib_macro" }
xml = "1.2.1"
lazy_static = "1.5.0"

# used in devel: linux
arrayvec = "0.7.6"
fixedbitset = "0.5.7"

[target.'cfg(target_os="linux")'.dependencies]
rppal = { version = "0.22.1", features = ["hal", "nb"] }
dht11_gpio = "0.1.0"                                       # temperature sensor
lcd-lcm1602-i2c = "0.3.0"
max7219 = "0.4.2"
ws2812-spi = "0.5.1"
smart-leds-trait = "0.3.2"
smart-leds = "0.4.0"
smart_led_effects = "0.1.8"
rotary-encoder-embedded = "0.4.0"
pwm-pca9685 = "1.0.0"                                      # PWM 16-ch I2C
ssd1306 = "0.8.4"                                          # OLED display
vl53l0x = "1.0.1"                                          # laser distance sensor
ads1x1x = "0.3.0"                                          # I2C ADC 16-channel
irp = "0.3.4"                                              # infrared protocol support
mpu6050-dmp = "0.6.1"                                      # gyro+accelerometer
# mpr121-hal = { version = "0.5.0", features = ["sync"] }
mpr121-hal = { path = "../extra/mpr121-hal" }
pn532 = "0.5.0" 
users = "0.11"

[target.'cfg(windows)'.dependencies]
winprint = { version = "0.2.0" }
printers = { version = "2.3.0", default-features = false, features = [] }

[build-dependencies]
cbindgen = "0.28.0"
walkdir = "2.5.0"
