#!/bin/sh
ECHO=`which gecho`

if [ $# -ne 2 ]
then
    echo "Usage: $0 TCL_SOURCE FUNC_NAME"
    exit 1
fi

if [ ! -f "$1" ]
then
    echo "Tcl source file does not exists: $1"
    exit 2
fi

echo "/* This is autogenerated source file. Do not edit! */"
echo "#ifndef $2_h"
echo "#define $2_h"
echo "#include \"m_pd.h\""
echo ""

echo "void $2() {"
echo "    sys_gui("
cat "$1" | sed -e 's|\\|\\\\|g' -e 's|"|\\"|g' -e 's|\(.*\)|    "\1\\n"|' -e '/^ *"#/d' -e '/^ *"\\n"/d'
echo "    );"
echo "}"
echo "#endif"

