// this is autogenerated file, do not edit manually!
#include "m_pd.h"
#ifndef __ui_icon_tcl_h
#define __ui_icon_tcl_h
namespace {
void ui_icon_tcl_output() {
	sys_vgui("%s", "namespace eval ::ui {\nnamespace eval icon {\nvariable png_support True\nproc create_image {name data18 data24 data36 data48} {\nif { !$::ui::icon::png_support } { return }\nif { [catch { image create photo ${name}_18 -width 18 -height 18 -data $data18\nimage create photo ${name}_24 -width 24 -height 24 -data $data24\nimage create photo ${name}_36 -width 36 -height 36 -data $data36\nimage create photo ${name}_48 -width 48 -height 48 -data $data48}] } {\n::pdwindow::error \"\\[ui.icon\\] no PNG image support, can't create icons\\n\"\nset ::ui::icon::png_support False\n}\n}\nproc update {cnv id w h name color} {\nset c [::ceammc::ui::widget_canvas $cnv $id]\nset t [::ceammc::ui::widget_tag $id]\n$c delete $t\nif { $::ui::icon::png_support } {\n$c create rectangle 0 0 $w $h -outline {} -width 0 -fill $color -tags $t\n$c create image 0 0 -anchor nw -image $name -tags $t\n} else {\n$c create rectangle 1 1 [expr $w-1] [expr $h-1] -outline black -width 1 -fill grey -tags $t\n}\n}\n}\n}\n");
}
}
#endif // __ui_icon_tcl_h
