/* This is autogenerated source file. Do not edit! */
#ifndef uilink_tcl_init_h
#define uilink_tcl_init_h
#include <m_pd.h>

void uilink_tcl_init() {
    sys_gui("proc ceammclink_open {filename dir} {\n");
    sys_gui("if {[string first \"://\" $filename] > -1} {\n");
    sys_gui("menu_openfile $filename\n");
    sys_gui("} elseif {[file pathtype $filename] eq \"absolute\"} {\n");
    sys_gui("if {[file extension $filename] eq \".pd\"} {\n");
    sys_gui("set dir [file dirname $filename]\n");
    sys_gui("set name [file tail $filename]\n");
    sys_gui("menu_doc_open $dir $name\n");
    sys_gui("} else {\n");
    sys_gui("menu_openfile $filename\n");
    sys_gui("}\n");
    sys_gui("} elseif {[file exists [file join $dir $filename]]} {\n");
    sys_gui("set fullpath [file normalize [file join $dir $filename]]\n");
    sys_gui("set dir [file dirname $fullpath]\n");
    sys_gui("set filename [file tail $fullpath]\n");
    sys_gui("menu_doc_open $dir $filename\n");
    sys_gui("} else {\n");
    sys_gui("bell ; # beep on error to provide instant feedback\n");
    sys_gui("pdtk_post \"[ui.link] ERROR file not found: $filename at $dirn\"\n");
    sys_gui("}\n");
    sys_gui("}\n");
}
#endif
