// this is autogenerated file, do not edit manually!
#include "m_pd.h"
#ifndef __ui_number_tilde_tcl_h
#define __ui_number_tilde_tcl_h
namespace {
void ui_number_tilde_tcl_output() {
	sys_vgui("%s", "namespace eval ui {\nnamespace eval number_tilde {\nvariable font_size 11\nvariable font_family \"Helvetica\"\n}\nswitch -- $::windowingsystem {\n\"aqua\" { }\n\"x11\" { }\n\"win32\" {\nset number_tilde::font_size 8\n}\n}\nproc number_font { zoom } {\nreturn \"$number_tilde::font_family [expr $zoom * $number_tilde::font_size] normal roman\"\n}\nproc number_draw_box {c tag w h zoom bdcolor acolor tcolor value} {\nset x [expr $h * 0.7]\nset ft [number_font $zoom]\n$c create line $x 0 $x $h -width 1 -fill $bdcolor -tags $tag\nset tx [expr $x * 0.5]\nset ty [expr $h * 0.5]\n$c create text $tx $ty -text \"~\" -anchor center -justify center \\\n-font $ft -fill $acolor -width 0 -tags $tag\nset tx [expr $h * 0.9]\nset ty [expr $h * 0.55]\n$c create text $tx $ty -text $value -anchor w -justify left \\\n-font $ft -fill $tcolor -width 0 -tags $tag\n}\nproc number_update {cnv id w h zoom bdcolor acolor tcolor value} {\nset c [::ceammc::ui::widget_canvas $cnv $id]\nset t [::ceammc::ui::widget_tag $id]\n$c delete $t\nnumber_draw_box $c $t $w $h ");
	sys_vgui("%s", "$zoom $bdcolor $acolor $tcolor $value\n}\n}\n");
}
}
#endif // __ui_number_tilde_tcl_h
