#!/bin/sh

SHA256SUM="@SHA256SUM@"
EXTERNAL_ARCHIVE="@CEAMMC_EXTERNAL_NAME@"
INNO_SETUP_EXE="@INNO_INSTALLER_NAME@.exe"

cd "@PROJECT_BINARY_DIR@/dist"
$SHA256SUM $EXTERNAL_ARCHIVE $INNO_SETUP_EXE > checksums_win.sha256
