#define TK_PLUS                             1
#define TK_DIVIDE                           2
#define TK_TIMES                            3
#define TK_POW                              4
#define TK_MOD                              5
#define TK_MINUS                            6
#define TK_PROP_AMP                         7
#define TK_PROP_AT                          8
#define TK_PROP_LEN                         9
#define TK_PROP_SPEED                      10
#define TK_PROP_TIME_BEFORE                11
#define TK_PROP_TIME_AFTER                 12
#define TK_PROP_PAN                        13
#define TK_PROP_REPEATS                    14
#define TK_ONDONE                          15
#define TK_HANN                            16
#define TK_RECT                            17
#define TK_TRI                             18
#define TK_TRPZ                            19
#define TK_OPENP                           20
#define TK_DOUBLE                          21
#define TK_CLOSEP                          22
#define TK_PROP_TAG                        23
#define TK_SYMBOL                          24
#define TK_PROP_INTERP                     25
#define TK_PROP_WINDOW                     26
#define TK_MODULATE                        27
#define TK_OVERFLOW                        28
#define TK_CLIP                            29
#define TK_FOLD                            30
#define TK_WRAP                            31
#define TK_NONE                            32
#define TK_LINEAR                          33
#define TK_CUBIC                           34
#define TK_MODE                            35
#define TK_FN_SQRT                         36
#define TK_SIN                             37
#define TK_SAW                             38
#define TK_SQR                             39
#define TK_DOTS                            40
#define TK_CONST_AMP                       41
#define TK_CONST_AT                        42
#define TK_CONST_LEN                       43
#define TK_CONST_PAN                       44
#define TK_CONST_SPEED                     45
#define TK_CONST_TIME_BEFORE               46
#define TK_CONST_TIME_AFTER                47
#define TK_CONST_SR                        48
#define TK_CONST_BS                        49
#define TK_CONST_ASIZE                     50
#define TK_CONST_NITER                     51
#define TK_CONST_NBLOCK                    52
#define TK_CONST_NSAMP                     53
#define TK_CONST_GIDX                      54
#define TK_ASSIGN_ADD                      55
#define TK_ASSIGN_SUB                      56
#define TK_ASSIGN_MUL                      57
#define TK_ASSIGN_SET                      58
#define TK_FN_ABS                          59
#define TK_FN_COS                          60
#define TK_FN_TAN                          61
#define TK_FN_ACOS                         62
#define TK_FN_ASIN                         63
#define TK_FN_ATAN                         64
#define TK_FN_CEIL                         65
#define TK_FN_FLOOR                        66
#define TK_FN_ROUND                        67
#define TK_FN_LOG                          68
#define TK_FN_LOG10                        69
#define TK_FN_LOG2                         70
#define TK_FN_FRAC                         71
#define TK_COMMA                           72
#define TK_FN_URAND                        73
#define TK_CHOICE                          74
#define TK_SAMP                            75
#define TK_MSEC                            76
#define TK_SEC                             77
