#define TK_PLUS                             1
#define TK_DIVIDE                           2
#define TK_TIMES                            3
#define TK_POW                              4
#define TK_MOD                              5
#define TK_MINUS                            6
#define TK_PROP_AMP                         7
#define TK_PROP_AT                          8
#define TK_PROP_LEN                         9
#define TK_PROP_SPEED                      10
#define TK_PROP_TIME_BEFORE                11
#define TK_PROP_TIME_AFTER                 12
#define TK_PROP_PAN                        13
#define TK_PROP_REPEATS                    14
#define TK_ONDONE                          15
#define TK_HANN                            16
#define TK_RECT                            17
#define TK_TRI                             18
#define TK_PROP_TAG                        19
#define TK_SYMBOL                          20
#define TK_PROP_INTERP                     21
#define TK_PROP_WINDOW                     22
#define TK_MODULATE                        23
#define TK_OVERFLOW                        24
#define TK_CLIP                            25
#define TK_FOLD                            26
#define TK_WRAP                            27
#define TK_NONE                            28
#define TK_LINEAR                          29
#define TK_CUBIC                           30
#define TK_MODE                            31
#define TK_FN_SQRT                         32
#define TK_SIN                             33
#define TK_SAW                             34
#define TK_SQR                             35
#define TK_DOTS                            36
#define TK_OPENP                           37
#define TK_CLOSEP                          38
#define TK_CONST_AMP                       39
#define TK_CONST_AT                        40
#define TK_CONST_LEN                       41
#define TK_CONST_PAN                       42
#define TK_CONST_SPEED                     43
#define TK_CONST_TIME_BEFORE               44
#define TK_CONST_TIME_AFTER                45
#define TK_CONST_SR                        46
#define TK_CONST_BS                        47
#define TK_CONST_ASIZE                     48
#define TK_CONST_NITER                     49
#define TK_CONST_NBLOCK                    50
#define TK_CONST_NSAMP                     51
#define TK_CONST_GIDX                      52
#define TK_ASSIGN_ADD                      53
#define TK_ASSIGN_SUB                      54
#define TK_ASSIGN_MUL                      55
#define TK_ASSIGN_SET                      56
#define TK_FN_ABS                          57
#define TK_FN_COS                          58
#define TK_FN_TAN                          59
#define TK_FN_ACOS                         60
#define TK_FN_ASIN                         61
#define TK_FN_ATAN                         62
#define TK_FN_CEIL                         63
#define TK_FN_FLOOR                        64
#define TK_FN_ROUND                        65
#define TK_FN_LOG                          66
#define TK_FN_LOG10                        67
#define TK_FN_LOG2                         68
#define TK_FN_FRAC                         69
#define TK_COMMA                           70
#define TK_FN_URAND                        71
#define TK_DOUBLE                          72
#define TK_CHOICE                          73
#define TK_SAMP                            74
#define TK_MSEC                            75
#define TK_SEC                             76
