#define TK_PLUS                             1
#define TK_DIVIDE                           2
#define TK_TIMES                            3
#define TK_POW                              4
#define TK_MOD                              5
#define TK_MINUS                            6
#define TK_PROP_AMP                         7
#define TK_PROP_AT                          8
#define TK_PROP_LEN                         9
#define TK_PROP_SPEED                      10
#define TK_PROP_TIME_BEFORE                11
#define TK_PROP_TIME_AFTER                 12
#define TK_PROP_PAN                        13
#define TK_PROP_REPEATS                    14
#define TK_ONDONE                          15
#define TK_HANN                            16
#define TK_RECT                            17
#define TK_TRI                             18
#define TK_TRPZ                            19
#define TK_OPENP                           20
#define TK_DOUBLE                          21
#define TK_CLOSEP                          22
#define TK_LINUP                           23
#define TK_LINDOWN                         24
#define TK_PROP_TAG                        25
#define TK_SYMBOL                          26
#define TK_PROP_INTERP                     27
#define TK_PROP_WINDOW                     28
#define TK_MODULATE                        29
#define TK_OVERFLOW                        30
#define TK_CLIP                            31
#define TK_FOLD                            32
#define TK_WRAP                            33
#define TK_NONE                            34
#define TK_LINEAR                          35
#define TK_CUBIC                           36
#define TK_MODE                            37
#define TK_FN_SQRT                         38
#define TK_SIN                             39
#define TK_SQR                             40
#define TK_USAW                            41
#define TK_DSAW                            42
#define TK_DOTS                            43
#define TK_CONST_AMP                       44
#define TK_CONST_AT                        45
#define TK_CONST_LEN                       46
#define TK_CONST_PAN                       47
#define TK_CONST_SPEED                     48
#define TK_CONST_TIME_BEFORE               49
#define TK_CONST_TIME_AFTER                50
#define TK_CONST_SR                        51
#define TK_CONST_BS                        52
#define TK_CONST_ASIZE                     53
#define TK_CONST_NITER                     54
#define TK_CONST_NBLOCK                    55
#define TK_CONST_NSAMP                     56
#define TK_CONST_GIDX                      57
#define TK_ASSIGN_ADD                      58
#define TK_ASSIGN_SUB                      59
#define TK_ASSIGN_MUL                      60
#define TK_ASSIGN_SET                      61
#define TK_FN_ABS                          62
#define TK_FN_COS                          63
#define TK_FN_TAN                          64
#define TK_FN_ACOS                         65
#define TK_FN_ASIN                         66
#define TK_FN_ATAN                         67
#define TK_FN_CEIL                         68
#define TK_FN_FLOOR                        69
#define TK_FN_ROUND                        70
#define TK_FN_LOG                          71
#define TK_FN_LOG10                        72
#define TK_FN_LOG2                         73
#define TK_FN_FRAC                         74
#define TK_COMMA                           75
#define TK_FN_URAND                        76
#define TK_CHOICE                          77
#define TK_SAMP                            78
#define TK_MSEC                            79
#define TK_SEC                             80
