option(WITH_COVERAGE  "Build with coverage and profiling flags" OFF)
option(WITH_FLUIDLITE "Build with FluidLite support" TRUE)
option(WITH_EXPERIMENTAL "Build with experimental objects" OFF)
option(WITH_BENCHMARK "Build with benchmarks" ON)
option(WITH_PCRE2 "Build with PCRE2 library" ON)
