pkg_check_modules(GLIB_PKG glib-2.0)

if (GLIB_PKG_FOUND)
  find_path(GLIB_INCLUDE_DIR  NAMES glib.h PATH_SUFFIXES glib-2.0
    PATHS
    ${GLIB_PKG_INCLUDE_DIRS}
    )
  find_path(GLIB_CONFIG_INCLUDE_DIR NAMES glibconfig.h PATHS ${GLIB_PKG_LIBDIR} PATH_SUFFIXES glib-2.0/include)
  find_library(GLIB_LIBRARIES2 NAMES glib-2.0
    PATHS
    ${GLIB_PKG_LIBRARY_DIRS}
    )

  find_library(GOBJECT_LIBRARIES NAMES gobject-2.0
    PATHS
    ${GLIB_PKG_LIBRARY_DIRS}
    )

  find_library(GTHREAD_LIBRARIES NAMES gthread-2.0
    PATHS
    ${GLIB_PKG_LIBRARY_DIRS}
    )

  set(GLIB_LIBRARIES ${GLIB_LIBRARIES2} ${GOBJECT_LIBRARIES} ${GTHREAD_LIBRARIES})

else ()
  message (FATAL_ERROR "pkg-config is needed")
  return()
endif ()

if (GLIB_INCLUDE_DIR AND GLIB_CONFIG_INCLUDE_DIR AND GLIB_LIBRARIES)
  set(GLIB_INCLUDE_DIRS ${GLIB_INCLUDE_DIR} ${GLIB_CONFIG_INCLUDE_DIR})
endif ()

if(GLIB_INCLUDE_DIRS AND GLIB_LIBRARIES)
  set(GLIB_FOUND TRUE CACHE INTERNAL "glib-2.0 found")
  message(STATUS "Found glib-2.0: ${GLIB_INCLUDE_DIR}, ${GLIB_LIBRARIES}")
else()
  set(GLIB_FOUND FALSE CACHE INTERNAL "glib-2.0 found")
  message(STATUS "glib-2.0 not found.")
endif()

mark_as_advanced(GLIB_INCLUDE_DIR GLIB_CONFIG_INCLUDE_DIR GLIB_INCLUDE_DIRS GLIB_LIBRARIES)
