set(PDDIR "pd_ceammc")

if(WIN32 OR MSYS OR MINGW)
    set(PD_EXE_INSTALL_PATH bin)
    set(PD_SEND_INSTALL_PATH bin)
    set(PD_RECEIVE_INSTALL_PATH bin)
    set(PDCORE_LIB_INSTALL_PATH bin)
    set(PD_DOC_INSTALL_PATH .)
    set(PD_TCL_INSTALL_PATH .)
    set(PD_LIBTCL_INSTALL_PATH lib)
    set(PD_PO_INSTALL_PATH po)
    set(PD_GUI_PLUGINS_PATH tcl)
    set(PD_INCLUDE_INSTALL_PATH include)
    set(PD_INTERNAL_EXT_INSTALL_PATH extra)
else()
    set(PD_EXE_INSTALL_PATH lib/${PDDIR}/bin)
    set(PD_SEND_INSTALL_PATH lib/${PDDIR}/bin)
    set(PD_RECEIVE_INSTALL_PATH lib/${PDDIR}/bin)
    set(PD_WATCHDOG_INSTALL_PATH lib/${PDDIR}/bin)
    set(PDCORE_LIB_INSTALL_PATH lib)
    set(PD_DOC_INSTALL_PATH lib/${PDDIR})
    set(PD_TCL_INSTALL_PATH lib/${PDDIR})
    set(PD_PO_INSTALL_PATH lib/${PDDIR}/po)
    set(PD_GUI_PLUGINS_PATH lib/${PDDIR}/tcl)
    set(PD_INTERNAL_EXT_INSTALL_PATH lib/${PDDIR}/extra)
    set(PD_INCLUDE_INSTALL_PATH include/${PDDIR})
endif()


