if(APPLE)
    set(CPACK_GENERATOR "ZIP;")
    SET(CPACK_SOURCE_GENERATOR "TGZ;")
endif()

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "PureData")
set(CPACK_PACKAGE_VENDOR "http://ceammc.com")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/README.txt")
set(CPACK_PACKAGE_VERSION_MAJOR ${PD_MAJOR_VERSION})
set(CPACK_PACKAGE_VERSION_MINOR ${PD_MINOR_VERSION})
set(CPACK_PACKAGE_VERSION_PATCH "${PD_BUGFIX_VERSION}_ceammc")

SET(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${CMake_VERSION_MAJOR}.${CMake_VERSION_MINOR}")

include(CPack)
