message(STATUS "===========================================")
message(STATUS "Configure summary:")
message(STATUS "===========================================")
message(STATUS "  Version:          ${PD_TEXT_VERSION_FULL}")
message(STATUS "  Audio:")
message(STATUS "       alsa:        ${WITH_ALSA}")
message(STATUS "       dummy:       ${WITH_DUMMY_AUDIO}")
message(STATUS "       jack:        ${WITH_JACK}")
message(STATUS "       portaudio:   ${WITH_PORTAUDIO}")
message(STATUS "       oss:         ${WITH_OSS_AUDIO}")
message(STATUS "       mmio:        ${WITH_MMIO}")
message(STATUS "  MIDI:")
message(STATUS "       alsa:        ${WITH_ALSA_MIDI}")
message(STATUS "       dummy:       ${WITH_DUMMY_MIDI}")
message(STATUS "       portmidi:    ${WITH_PORTMIDI}")
message(STATUS "       oss:         ${WITH_OSS_MIDI}")
message(STATUS "===========================================")
message(STATUS "Build info:")
message(STATUS "===========================================")
message(STATUS "  Coverage:         ${WITH_COVERAGE}")
message(STATUS "")

