name: pd-ceammc
version: "2023.01"
license: "GPL-3.0"
summary: "Pure Data CEAMMC distribution"
description: |
    Pure Data CEAMMC distribution and library of externals used for work
    and education purposes in Centre of electoacoustic music of
    Moscow Conservatory (CEAMMC) and ZIL-electro studio.
icon: ceammc/gui/icons/puredata-ceammc.png
grade: stable
confinement: strict
base: core20

architectures:
    - build-on: amd64
    # - build-on: i386
    #- build-on: armhf

environment:
    TCL_LIBRARY: ${SNAP}/usr/share/tcltk/tcl8.6
    TK_LIBRARY:  "${SNAP}/usr/share/tcltk/tk8.6 ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET} ${SNAP}/usr/lib/tcltk/${SNAPCRAFT_ARCH_TRIPLET}"

layout:
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
        bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
    /etc/asound.conf:
        bind-file: $SNAP/etc/alsa.conf
    /usr/share/alsa/alsa.conf:
        bind-file: $SNAP/usr/share/alsa/alsa.conf

apps:
    pd-ceammc:
        command: usr/bin/pd.wrapper
        common-id: com.ceammc.pd
        plugs:
            - alsa
            - pulseaudio # for audio output
            - jack1
            - home
            - unity7
            - x11
            - network
            - desktop # for TCL-TK working
            - desktop-legacy
            - removable-media # for alsa device access
        #desktop: ceammc/distrib/linux/snap/pd-ceammc.desktop
    pdsend:
        command: usr/lib/pd_ceammc/bin/pdsend
        plugs: [ network ]
    pdreceive:
        command: usr/lib/pd_ceammc/bin/pdreceive
        plugs: [ network ]

parts:
    fix-hardcoded:
        plugin: nil
        after: [ wrappers ]
        override-build: |
            echo "Fixing hardcoded libtk path ... "
            find ${SNAPCRAFT_STAGE}/usr/lib -name pkgIndex.tcl
            fsname="usr/lib/tcltk/${SNAPCRAFT_ARCH_TRIPLET}/tk8.6/pkgIndex.tcl"
            file="${SNAPCRAFT_STAGE}/${fsname}"
            sed -i "s|file join /usr/lib/${SNAPCRAFT_ARCH_TRIPLET} libtk8.6.so|file join {} libtk8.6.so|" $file
    wrappers:
        plugin: dump
        after: [ pd-ceammc ]
        source: ceammc/distrib/linux/snap
        organize:
            pd.wrapper: /usr/bin/pd.wrapper

    alsa:
        plugin: nil
        source: https://github.com/diddledan/snapcraft-alsa.git
        override-pull: |
            cat > alsa.conf <<EOF
            pcm.!default {
            type pulse
            fallback "sysdefault"
            hint {
                show on
                description "Default ALSA Output (currently PulseAudio Sound Server)"
            }
            }
            ctl.!default {
            type pulse
            fallback "sysdefault"
            }
            EOF
        override-build: |
            install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc alsa.conf
        stage-packages:
            - libasound2
            - libasound2-plugins

    pd-ceammc:
        plugin: cmake
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/usr
            - -DWITH_PORTAUDIO=OFF
            - -DWITH_BENCHMARK=OFF
            - -DWITH_ALSA_AUDIO=ON
            - -DWITH_ALSA_MIDI=ON
            - -DWITH_JACK=ON
            - -DENABLE_TESTS=OFF
            - -DWITH_EXT_FLEXT=OFF
        source: .
        build-packages:
            - alsa-utils
            - build-essential
            - cmake
            - g++
            - gettext
            - libarmadillo-dev
            - libasound2-dev
            - libavahi-compat-libdnssd-dev
            - libboost-dev
            - libfftw3-dev
            - libglib2.0-dev
            - libjack-jackd2-dev
            - libluajit-5.1-dev
            - libmodplug-dev
            - librubberband-dev
            - libsamplerate0-dev
            - libsndfile1-dev
            - libxcb-randr0-dev
            - libxcb-util-dev
            - libxcb1-dev
            - llvm-dev
            - lsb-release
            - make
            - patchelf
            - pkg-config
            - tcl-dev
            - tcllib
            - tk-dev
            - tklib
            - x11proto-dev
        stage-packages:
            - libasound2
            - libatm1
            - libfftw3-single3
            - libice6
            - libjack-jackd2-0
            - libluajit-5.1-2
            - libluajit-5.1-common
            - libmodplug1
            - librubberband2
            - libsamplerate0
            - libsndfile1
            - libtcl8.6
            - libxcb-randr0
            - libxtables12
            - llvm
            - llvm-runtime
            - tcl
            - tcllib
            - tk
            - tklib
