[package]
name = "proto_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
log = "0.4.21"
env_logger = "0.11.3"
obws = "0.13.0"
# tokio = { version = "1.28", features = ["rt", "rt-multi-thread", "signal", "sync", "fs"] }
tokio = { version = "1.28.0", features = ["rt", "sync", "rt-multi-thread"] }
function_name = "0.3.0"

[build-dependencies]
cbindgen = "0.22.0"
