#ifndef ceammc_rust_proto_h
#define ceammc_rust_proto_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstddef>
#include <cstdint>
#include <type_traits>

namespace ceammc {
namespace proto_rust {
template <typename T>
class Option {
    static_assert(std::is_default_constructible<T>::value, "Type should have static constructor");
    T value_;
    bool is_set_ { false };

public:
    Option()
        : value_ {}
    {
    }

    void set(const T& value)
    {
        value_ = value;
        is_set_ = true;
    }

    inline const T* get() const
    {
        return is_set_ ? &value_ : nullptr;
    }
};
} // namespace proto_rust
} // namespace ceammc


enum class ceammc_rust_atom_type : uint8_t {
    Float,
    String,
    Null,
};

enum class ceammc_vlc_sort_order {
    Normal,
    Reversed,
};

/// vlc playing state
enum class ceammc_vlc_state : uint8_t {
    Unknown,
    Stopped,
    Paused,
    Playing,
};

struct ceammc_obs_client;

struct ceammc_obs_collection_list;

struct ceammc_obs_info;

struct ceammc_obs_monitor;

struct ceammc_obs_monitor_list;

struct ceammc_obs_scene;

struct ceammc_obs_scene_item;

struct ceammc_obs_scene_item_list;

struct ceammc_obs_scene_list;

/// vlc control handle
struct ceammc_vlc;

struct ceammc_obs_init {
    const char *host;
    const char *password;
    uint16_t port;
};

struct ceammc_callback_msg {
    void *user;
    void (*cb)(void *user, const char *msg);
};

struct ceammc_obs_result_cb {
    /// user data pointer (can be NULL)
    void *user;
    /// info callback function (can be NULL)
    void (*cb_info)(void *user, const ceammc_obs_info *info);
    /// collection list callback function (can be NULL)
    void (*cb_collection_list)(void *user, const ceammc_obs_collection_list *coll);
    /// scene list callback function (can be NULL)
    void (*cb_scene_list)(void *user, const ceammc_obs_scene_list *scl);
    /// scene itme list callback function (can be NULL)
    void (*cb_scene_item_list)(void *user, const ceammc_obs_scene_item_list *items);
    /// monitor list callback function (can be NULL)
    void (*cb_monitor_list)(void *user, const ceammc_obs_monitor_list *mons);
    /// current collection callback function (can be NULL)
    void (*cb_current_collection)(void *user, const char *name);
    /// current scene callback function (can be NULL)
    void (*cb_current_scene)(void *user, const char *name);
    /// connected/disconnected callback function (can be NULL)
    void (*cb_connected)(void *user, bool state);
};

struct ceammc_callback_notify {
    size_t id;
    void (*cb)(size_t id);
};

struct ceammc_vlc_status {
    double position;
    double volume;
    double time;
    double length;
    double rate;
    ceammc_vlc_state state;
    uint8_t apiversion;
    bool has_loop;
    bool repeat;
    bool random;
    bool fullscreen;
};

struct ceammc_vlc_status_cb {
    /// user data
    void *user;
    /// callback function
    void (*cb)(void *user, const ceammc_vlc_status *status);
};

union ceammc_rust_value {
    const char *str_val;
    double float_val;
};

struct ceammc_rust_atom {
    ceammc_rust_value data;
    ceammc_rust_atom_type atom_type;
};


extern "C" {

/// create new empty OBS scene
/// @param cli - pointer to obs client
/// @param name - scene name
/// @return true on success, false on error
bool ceammc_obs_create_scene(const ceammc_obs_client *cli, const char *name);

/// enable OBS scene item
/// @param cli - pointer to obs client
/// @param scene - scene name
/// @param idx - item index
bool ceammc_obs_enable_scene_item(const ceammc_obs_client *cli,
                                  const char *scene,
                                  size_t idx,
                                  bool enabled);

/// change to first OBS scene
/// @param cli - pointer to obs client
/// @return true on success, false on error
bool ceammc_obs_first_scene(const ceammc_obs_client *cli);

/// free OBS Studio client
/// @param cli - pointer to obs client
void ceammc_obs_free(ceammc_obs_client *cli);

/// get OBS version
/// @param v - pointer to version struct
/// @param major - pointer to store major version data
/// @param minor - pointer to store minor version data
/// @param patch - pointer to store patch version data
void ceammc_obs_get_app_version(const ceammc_obs_info *v,
                                uint64_t *major,
                                uint64_t *minor,
                                uint64_t *patch);

/// get OBS collection at
/// @param coll - pointer to collection list (not NULL!)
/// @param idx - collection index
/// @return NULL if not found
const char *ceammc_obs_get_collection_at(const ceammc_obs_collection_list *coll, size_t idx);

/// get OBS collection count
/// @param coll - pointer to collection list (not NULL!)
size_t ceammc_obs_get_collection_count(const ceammc_obs_collection_list *coll);

/// get OBS collection current
/// @param coll - pointer to collection list (not NULL!)
const char *ceammc_obs_get_collection_current(const ceammc_obs_collection_list *coll);

/// get OBS image format at
/// @param v - pointer to version struct
/// @param idx - image format index
const char *ceammc_obs_get_image_format_at(const ceammc_obs_info *v, size_t idx);

/// get OBS image format count
/// @param v - pointer to version struct
size_t ceammc_obs_get_image_format_count(const ceammc_obs_info *v);

/// get monitor at specified position
/// @param ml - pointer to monitor list (not NULL!)
/// @return pointer to monitor or nullptr if not found
const ceammc_obs_monitor *ceammc_obs_get_monitor_at(const ceammc_obs_monitor_list *ml, size_t idx);

/// get monitor list length
/// @param ml - pointer to monitor list (not NULL!)
size_t ceammc_obs_get_monitor_count(const ceammc_obs_monitor_list *ml);

/// get monitor geometry
/// @param m - pointer to monitor (not NULL!)
/// @param x - pointer to store x coord
/// @param y - pointer to store y coord
/// @param w - pointer to store monitor width
/// @param h - pointer to store monitor height
void ceammc_obs_get_monitor_geom(const ceammc_obs_monitor *m,
                                 uint16_t *x,
                                 uint16_t *y,
                                 uint16_t *w,
                                 uint16_t *h);

/// get monitor index
/// @param m - pointer to monitor (not NULL!)
uint32_t ceammc_obs_get_monitor_index(const ceammc_obs_monitor *m);

/// get monitor name
/// @param m - pointer to monitor (not NULL!)
const char *ceammc_obs_get_monitor_name(const ceammc_obs_monitor *m);

/// get OBS platform
/// @param v - pointer to version struct
const char *ceammc_obs_get_platform(const ceammc_obs_info *v);

/// get OBS platform description
/// @param v - pointer to version struct
const char *ceammc_obs_get_platform_desc(const ceammc_obs_info *v);

/// get RPC OBS version
/// @param v - pointer to version struct
uint32_t ceammc_obs_get_rpc_version(const ceammc_obs_info *v);

/// get scene list data
/// @param scenes - pointer to scenes (not NULL!)
const ceammc_obs_scene *ceammc_obs_get_scene_at(const ceammc_obs_scene_list *scl, size_t idx);

/// get scene count
/// @param scenes - pointer to scenes (not NULL!)
size_t ceammc_obs_get_scene_count(const ceammc_obs_scene_list *scl);

/// get scene item at specified position
/// @param itl - pointer to item list (not NULL!)
/// @param idx - item position
const ceammc_obs_scene_item *ceammc_obs_get_scene_item_at(const ceammc_obs_scene_item_list *itl,
                                                          size_t idx);

/// get number of scene items
/// @param itl - pointer to item list (not NULL!)
size_t ceammc_obs_get_scene_item_count(const ceammc_obs_scene_item_list *itl);

/// get scene item index
/// @param item - pointer to item (not NULL!)
uint32_t ceammc_obs_get_scene_item_index(const ceammc_obs_scene_item *item);

/// get scene item input kind
/// @param item - pointer to item (not NULL!)
const char *ceammc_obs_get_scene_item_input_kind(const ceammc_obs_scene_item *item);

/// get scene item name
/// @param item - pointer to item (not NULL!)
const char *ceammc_obs_get_scene_item_name(const ceammc_obs_scene_item *item);

/// get scene item type
/// @param item - pointer to item (not NULL!)
const char *ceammc_obs_get_scene_item_type(const ceammc_obs_scene_item *item);

/// get scene name as C-string
/// @param scene - pointer to scene (not NULL!)
const char *ceammc_obs_get_scene_name(const ceammc_obs_scene *scene);

/// get scene UUID as C-string
/// @param scene - pointer to scene (not NULL!)
const char *ceammc_obs_get_scene_uuid(const ceammc_obs_scene *scene);

/// get OBS Web Socket version
/// @param v - pointer to version struct
/// @param major - pointer to store major version data
/// @param minor - pointer to store minor version data
/// @param patch - pointer to store patch version data
void ceammc_obs_get_websocket_version(const ceammc_obs_info *v,
                                      uint64_t *major,
                                      uint64_t *minor,
                                      uint64_t *patch);

/// change to last OBS scene
/// @param cli - pointer to obs client
/// @return true on success, false on error
bool ceammc_obs_last_scene(const ceammc_obs_client *cli);

/// list OBS scene collections
/// @param cli - pointer to obs client
bool ceammc_obs_list_collections(const ceammc_obs_client *cli);

/// request list of OBS studio monitors
/// @param cli - pointer to obs client
/// @return true on success, false on error
bool ceammc_obs_list_monitors(const ceammc_obs_client *cli);

/// list OBS scene items
/// @param cli - pointer to obs client
/// @param scene - scene name
bool ceammc_obs_list_scene_items(const ceammc_obs_client *cli, const char *name);

/// send version request to OBS studio
/// @param cli - pointer to obs client
/// @return true on success, false on error
bool ceammc_obs_list_scenes(const ceammc_obs_client *cli);

/// create OBS Studio client
/// @param params - connection params
/// @param cb_err - callback for error messages
/// @param cb_post - callback for post messages
/// @param cb_debug - callback for debug messages
/// @param cb_log - callback for log messages
/// @param cb_reply - reply callbacks
/// @param cb_notify - notification callback
/// @return pointer to obs client or NULL on error
ceammc_obs_client *ceammc_obs_new(ceammc_obs_init params,
                                  ceammc_callback_msg cb_err,
                                  ceammc_callback_msg cb_post,
                                  ceammc_callback_msg cb_debug,
                                  ceammc_callback_msg cb_log,
                                  ceammc_obs_result_cb cb_reply,
                                  ceammc_callback_notify cb_notify);

/// move to next OBS scene
/// @param cli - pointer to obs client
/// @return true on success, false on error
bool ceammc_obs_next_scene(const ceammc_obs_client *cli);

/// move to previous OBS scene
/// @param cli - pointer to obs client
/// @return true on success, false on error
bool ceammc_obs_prev_scene(const ceammc_obs_client *cli);

/// process all available results from OBS studio
/// @param cli - pointer to obs client client
/// @return true on success, false on error
bool ceammc_obs_process_events(ceammc_obs_client *cli);

/// remove OBS scene
/// @param cli - pointer to obs client
/// @param name - scene name
/// @return true on success, false on error
bool ceammc_obs_remove_scene(const ceammc_obs_client *cli, const char *name);

/// remove OBS scene item
/// @param cli - pointer to obs client
/// @param scene - scene name
/// @param idx - item index
bool ceammc_obs_remove_scene_item(const ceammc_obs_client *cli, const char *scene, size_t idx);

/// request current OBS collection
/// @param cli - pointer to obs client
bool ceammc_obs_request_current_collection(const ceammc_obs_client *cli);

/// send current OBS scene request
/// @param cli - pointer to obs client
/// @return true on success, false on error
bool ceammc_obs_request_current_scene(const ceammc_obs_client *cli);

/// send version request to OBS studio
/// @param cli - pointer to obs client
/// @return true on success, false on error
bool ceammc_obs_request_version(const ceammc_obs_client *cli);

/// get current scene
/// @param scenes - pointer to scenes (not NULL!)
const ceammc_obs_scene *ceammc_obs_scene_current(const ceammc_obs_scene_list *scl);

/// set current OBS collection
/// @param cli - pointer to obs client
/// @param name - collection name
bool ceammc_obs_set_current_collection(const ceammc_obs_client *cli, const char *name);

/// set current scene
/// @param cli - pointer to obs client
/// @param name - scene name
/// @return true on success, false on error
bool ceammc_obs_set_current_scene(ceammc_obs_client *cli, const char *name);

/// init rust env_logger
/// logger config is done with a RUST_LOG env variable
void ceammc_proto_log_init();

/// add URI into vlc playlist
/// @param vlc - vlc control handle
/// @param uri - resource URI
/// @param play - should immidiately play added url
bool ceammc_vlc_add_uri(ceammc_vlc *vlc, const char *uri, bool play);

/// clear current playlist
/// @param vlc - vlc control handle
bool ceammc_vlc_clear(ceammc_vlc *vlc);

/// create vlc control handle
/// @param host - vlc host name or ip address, if NULL use localhost
/// @param port - vlc http remote port
/// @param pass - vlc http password
/// @param notify - notification callback
ceammc_vlc *ceammc_vlc_create(const char *host,
                              uint16_t port,
                              const char *pass,
                              ceammc_callback_msg cb,
                              ceammc_callback_notify notify);

/// free vlc handle
/// @param vlc - vlc control handle
void ceammc_vlc_free(ceammc_vlc *vlc);

/// set vlc fullscreen mode
/// @param vlc - vlc control handle
/// @param value - fullscreen mode, if NULL toggles fullscreen
bool ceammc_vlc_fullscreen(ceammc_vlc *vlc, const bool *value);

/// get current vlc status
/// @param vlc - vlc control handle
bool ceammc_vlc_get_status(ceammc_vlc *vlc);

/// set vlc loop mode
/// @param vlc - vlc control handle
/// @param value - loop value, if NULL toggles loop mode
bool ceammc_vlc_loop(ceammc_vlc *vlc, const bool *value);

/// go to next item in the playlist and play it
/// @param vlc - vlc control handle
bool ceammc_vlc_next(ceammc_vlc *vlc);

/// pause vlc playback
/// @param vlc - vlc control handle
/// @param value - if true, pauses playback, otherwise resume. If NULL toggles pause mode
bool ceammc_vlc_pause(ceammc_vlc *vlc, const bool *value);

/// play playlist item
/// @param vlc - vlc control handle
/// @param id - pointer to track index, can be NULL
bool ceammc_vlc_play(ceammc_vlc *vlc, const int16_t *id);

/// set vlc playback rate
/// @param vlc - vlc control handle
/// @param rate - vlc playback rate
bool ceammc_vlc_playback_rate(ceammc_vlc *vlc, float rate);

/// get incoming messages from vlc
/// @param vlc - vlc control handle
/// @param on_msg - error message callback from worker thread
/// @param on_stat - vlc status callback
bool ceammc_vlc_poll(ceammc_vlc *vlc, ceammc_callback_msg on_msg, ceammc_vlc_status_cb on_stat);

/// go to previous item in the playlist and play it
/// @param vlc - vlc control handle
bool ceammc_vlc_prev(ceammc_vlc *vlc);

/// set vlc repeat mode
/// @param vlc - vlc control handle
/// @param value - repeat value, if NULL toggles repeat mode
bool ceammc_vlc_repeat(ceammc_vlc *vlc, const bool *value);

/// seek to specified time
/// @param vlc - vlc control handle
/// @param seek - seek time value
bool ceammc_vlc_seek(ceammc_vlc *vlc, ceammc_rust_atom seek);

/// sort playlist
/// @param vlc - vlc control handle
/// @param sort - sort field number, not NULL!
/// @param mode - sort mode: normal or reversed
bool ceammc_vlc_sort(ceammc_vlc *vlc, const char *sort, ceammc_vlc_sort_order mode);

/// stop vlc playback
/// @param vlc - vlc control handle
bool ceammc_vlc_stop(ceammc_vlc *vlc);

/// set vlc volume
/// supported syntax:[+, 10], [-, 10], [100, None] etc.
/// @param vlc - vlc control handle
/// @param v0 - first arg
/// @param v1 - second arg
bool ceammc_vlc_volume(ceammc_vlc *vlc, ceammc_rust_atom v0, ceammc_rust_atom v1);

}  // extern "C"

#endif  // ceammc_rust_proto_h
