set(DOC_FILES
    array.copy
    array.do
    array.each
    array.fill
    array.minmax
    array.p2s
    array.s2p
    conv.bpm2hz
    conv.bpm2ms
    conv.bpm2sec
    conv.cc2amp
    conv.lin2curve
    conv.lin2exp
    conv.lin2lin
    conv.samp2sec
    conv.sec2samp
    conv.sec2str
    conv.str2sec
    data.fifo
    data.list
    data.set
    data.set2list
    dyn.comp2~
    dyn.comp~
    dyn.gate2~
    dyn.gate~
    dyn.limit2~
    dyn.limit~
    dyn.softclip~
    env.adsr~
    env.ar~
    env.follow~
    expand_env
    flow.change
    flow.group
    flow.pass
    flow.pass_if
    flow.reject
    flow.reject_if
    flow.split
    flow.sync
    flt.biquad~
    flt.bpf12~
    flt.bpf24~
    flt.c_bpf~
    flt.c_highshelf~
    flt.c_hpf~
    flt.c_lowshelf~
    flt.c_lpf~
    flt.c_notch~
    flt.c_peak~
    flt.dcblock2~
    flt.dcblock~
    flt.eq_peak~
    flt.highshelf~
    flt.hpf12~
    flt.hpf24~
    flt.lowshelf~
    flt.lpf12~
    flt.lpf24~
    flt.notch~
    flt.resonbp~
    function
    function.call
    fx.distortion~
    fx.flanger~
    fx.freeverb2~
    fx.freeverb~
    fx.freqshift~
    fx.pitchshift~
    fx.zita_rev1~
    global.float
    global.int
    global.list
    is_any
    is_bang
    is_even
    is_file
    is_float
    is_list
    is_odd
    is_pointer
    is_symbol
    lfo.impulse~
    lfo.square~
    lfo.tri~
    list.all_of
    list.any_of
    list.apply_to
    list.at
    list.choice
    list.count
    list.count_if
    list.deinterleave
    list.delta
    list.each
    list.equal
    list.first
    list.gen
    list.integrator
    list.interleave
    list.last
    list.length
    list.max
    list.mean
    list.min
    list.none_of
    list.normalize
    list.product
    list.range
    list.reduce
    list.remove_if
    list.resize
    list.reverse
    list.rotate
    list.seq
    list.shuffle
    list.sort
    list.sort_with
    list.sum
    list.unpack
    list.unwrap
    list.walk
    list.wrap
    live.capture~
    local.float
    local.int
    math.abs
    math.acos
    math.acosh
    math.and
    math.approx
    math.asin
    math.asinh
    math.atan
    math.atanh
    math.cbrt
    math.ceil
    math.cos
    math.cosh
    math.e
    math.exp
    math.exp2
    math.floor
    math.gcd
    math.inf
    math.lcm
    math.log
    math.log10
    math.log2
    math.nan
    math.neg
    math.or
    math.pi
    math.reciprocal
    math.round
    math.sign
    math.sin
    math.sinh
    math.sqrt
    math.squared
    math.tan
    math.tanh
    math.trunc
    msg
    noise.pink~
    noise.white~
    osc.impulse~
    osc.pulse~
    osc.saw~
    osc.sinfb~
    osc.square~
    osc.tri~
    path.basename
    path.dirname
    path.exists
    prop.get
    prop.set
    random.gauss
    random.int
    random.float
    replace
    set.contains
    set.diff
    set.equal
    set.intersect
    set.size
    set.symdiff
    set.union
    snd.file
    string
    string.contains
    string.ends_with
    string.equal
    string.format
    string.join
    string.length
    string.remove
    string.replace
    string.split
    string.substr
    string.starts_with
    string2symbol
    symbol.equal
    symbol.length
    system.getenv
    system.hostname
    system.memsize
    system.memused
    system.screen_size
    tl.bang
    tl.cue
    tl.transport
    ui.bang
    ui.bpfunc
    ui.display
    ui.keyboard
    ui.knob
    ui.matrix
    ui.scope~
    ui.slider2d
    ui.sliders
    ui.spectroscope~
    ui.toggle
    vector.distance
    vector.dot
    vector.length
    vector.normalize
)
