// this is autogenerated file, do not edit!
#ifndef MISC_WHISPER_TILDE_ARGS_HPP_
#define MISC_WHISPER_TILDE_ARGS_HPP_

#include "ceammc_atomlist_view.h"
#include "ceammc_object.h"
#include "datatype_color.h"

using namespace ceammc;

namespace {
struct m_clear_args {
    enum ArgProcessState { NOT_ENOUGH_ARGS = -3, INVALID_VALUE = -1 };
    // methods
    static const char* usage() {
        return "usage: [clear(";
    }
    static void output_usage(const BaseObject* obj) {
        Post(obj) << usage();
    }
    static void output_usage_verbose(const BaseObject* obj) {
        Error(obj) << usage();
    }
    bool parse_args(const AtomListView& lv, const BaseObject* obj, bool print_err = true) {
        int matched = 0;
        AtomListView left_args = lv.arguments();
        // check extra arguments
        if (left_args.size()) {
            if (print_err) {
                Error(obj) << "[clear( " << left_args.size() << " unexpected extra arguments were found: " << left_args;
                output_usage(obj);
            }
            return false;
        }
        return true;
    }
};

const char* m_clear_args_info() {
    return "clear the internal audio buffer";
}
void m_clear_args_info_output(const BaseObject* obj) {
    logpost(obj ? static_cast<void*>(obj->owner()) : nullptr,
        PD_NORMAL, "%s", m_clear_args_info());
}
struct m_recognize_args {
    enum ArgProcessState { NOT_ENOUGH_ARGS = -3, INVALID_VALUE = -1 };
    // methods
    static const char* usage() {
        return "usage: [recognize(";
    }
    static void output_usage(const BaseObject* obj) {
        Post(obj) << usage();
    }
    static void output_usage_verbose(const BaseObject* obj) {
        Error(obj) << usage();
    }
    bool parse_args(const AtomListView& lv, const BaseObject* obj, bool print_err = true) {
        int matched = 0;
        AtomListView left_args = lv.arguments();
        // check extra arguments
        if (left_args.size()) {
            if (print_err) {
                Error(obj) << "[recognize( " << left_args.size() << " unexpected extra arguments were found: " << left_args;
                output_usage(obj);
            }
            return false;
        }
        return true;
    }
};

const char* m_recognize_args_info() {
    return "start the process of recognizing the internal audio buffer";
}
void m_recognize_args_info_output(const BaseObject* obj) {
    logpost(obj ? static_cast<void*>(obj->owner()) : nullptr,
        PD_NORMAL, "%s", m_recognize_args_info());
}
struct m_record_args {
    enum ArgProcessState { NOT_ENOUGH_ARGS = -3, INVALID_VALUE = -1 };
    // methods
    static const char* usage() {
        return "usage: [record(";
    }
    static void output_usage(const BaseObject* obj) {
        Post(obj) << usage();
    }
    static void output_usage_verbose(const BaseObject* obj) {
        Error(obj) << usage();
    }
    bool parse_args(const AtomListView& lv, const BaseObject* obj, bool print_err = true) {
        int matched = 0;
        AtomListView left_args = lv.arguments();
        // check extra arguments
        if (left_args.size()) {
            if (print_err) {
                Error(obj) << "[record( " << left_args.size() << " unexpected extra arguments were found: " << left_args;
                output_usage(obj);
            }
            return false;
        }
        return true;
    }
};

const char* m_record_args_info() {
    return "start recording to the internal audio buffer";
}
void m_record_args_info_output(const BaseObject* obj) {
    logpost(obj ? static_cast<void*>(obj->owner()) : nullptr,
        PD_NORMAL, "%s", m_record_args_info());
}
struct m_stop_args {
    enum ArgProcessState { NOT_ENOUGH_ARGS = -3, INVALID_VALUE = -1 };
    // methods
    static const char* usage() {
        return "usage: [stop(";
    }
    static void output_usage(const BaseObject* obj) {
        Post(obj) << usage();
    }
    static void output_usage_verbose(const BaseObject* obj) {
        Error(obj) << usage();
    }
    bool parse_args(const AtomListView& lv, const BaseObject* obj, bool print_err = true) {
        int matched = 0;
        AtomListView left_args = lv.arguments();
        // check extra arguments
        if (left_args.size()) {
            if (print_err) {
                Error(obj) << "[stop( " << left_args.size() << " unexpected extra arguments were found: " << left_args;
                output_usage(obj);
            }
            return false;
        }
        return true;
    }
};

const char* m_stop_args_info() {
    return "stop recording to the internal audio buffer";
}
void m_stop_args_info_output(const BaseObject* obj) {
    logpost(obj ? static_cast<void*>(obj->owner()) : nullptr,
        PD_NORMAL, "%s", m_stop_args_info());
}
} // namespace 

#endif // MISC_WHISPER_TILDE_ARGS_HPP_
